import { notFound } from 'next/navigation';
import Brand from '@/app/components/Brand';
import CandidatePortalProfile from '@/app/components/CandidatePortalProfile';
import { rpc } from '@/lib/supabase-api';

export const dynamic='force-dynamic';

export default async function CandidatePortalPage({params}){
 const {token}=await params; const result=await rpc('xzrecruiter_candidate_portal_snapshot',{p_portal_token:token}).catch(()=>null); if(!result?.ok||!result.candidate)notFound(); const c=result.candidate;
 return <main className="candidate-portal"><header><Brand/><span className="status good">Secure candidate portal</span></header><section className="portal-hero"><span className="page-kicker">Your recruitment workspace</span><h1>{c.preferred_name||c.full_name}</h1><p>{c.headline||'Candidate profile'} · {c.city||c.country_code||'Global'}</p></section><CandidatePortalProfile token={token} candidate={c}/><div className="portal-grid"><section><h2>Applications</h2>{(result.applications||[]).length?(result.applications||[]).map((a)=><article className="portal-card" key={a.id}><div><b>{a.job_title}</b><span>{a.stage}</span></div><small>Updated {a.updated_at?new Date(a.updated_at).toLocaleString():'—'}</small></article>):<div className="ats-empty"><span>No active applications.</span></div>}</section><section><h2>Interviews</h2>{(result.interviews||[]).length?(result.interviews||[]).map((i)=><article className="portal-card" key={i.id}><div><b>{i.type}</b><span>{i.status}</span></div><small>{i.scheduled_at?new Date(i.scheduled_at).toLocaleString():'—'} · {i.timezone}</small>{i.meeting_url?<a href={i.meeting_url} rel="noreferrer">Open meeting link</a>:null}</article>):<div className="ats-empty"><span>No scheduled interviews.</span></div>}</section><section><h2>Offers</h2>{(result.offers||[]).length?(result.offers||[]).map((o)=><article className="portal-card" key={o.id}><div><b>{o.title||'Offer'}</b><span>{o.status}</span></div><small>{o.amount?`${o.currency||''} ${Number(o.amount).toLocaleString()}`:'Compensation shared separately'} · v{o.version}</small></article>):<div className="ats-empty"><span>No visible offers.</span></div>}</section></div><footer className="portal-security-note">This link is time-limited. XZRecruiter never exposes another candidate or workspace through this portal token.</footer></main>
}
