'use client';

import { useEffect, useState } from 'react';

async function ats(action,payload){const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}

export default function ApplicationScreeningDrawer({application,onClose,onRefresh}){
 const[detail,setDetail]=useState(null);const[answers,setAnswers]=useState([]);const[submission,setSubmission]=useState({summary:'',salaryExpectation:'',salaryCurrency:'',availability:'',noticePeriodDays:'',documentIds:[]});const[state,setState]=useState('loading');const[tab,setTab]=useState('screening');
 async function load(){setState('loading');try{const d=await ats('applicationCloseout',{applicationId:application.id});setDetail(d);setAnswers((d.screening||[]).map((x)=>({key:x.question_key,question:x.question_text,answer:typeof x.answer==='string'?x.answer:JSON.stringify(x.answer??''),score:x.score??'',knockout:Boolean(x.knockout)})));const s=d.submission||{};setSubmission({summary:s.summary||'',salaryExpectation:s.salary_expectation??d.application?.salary_expected??'',salaryCurrency:s.salary_currency||d.application?.salary_currency||d.application?.job_currency||'',availability:s.availability||d.application?.availability||'',noticePeriodDays:s.notice_period_days??d.application?.notice_period_days??'',documentIds:Array.isArray(s.document_ids)?s.document_ids:[]});setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[application.id]);
 function add(){setAnswers((a)=>[...a,{key:`custom_${Date.now()}`,question:'',answer:'',score:'',knockout:false}])}
 function update(i,field,value){setAnswers((a)=>a.map((x,n)=>n===i?{...x,[field]:value}:x))}
 async function saveScreening(){setState('saving');try{await ats('saveScreeningAnswers',{applicationId:application.id,answers:answers.filter((x)=>x.question.trim()).map((x)=>({key:x.key||`custom_${Math.random().toString(36).slice(2)}`,question:x.question,answer:x.answer,score:x.score===''?null:Number(x.score),knockout:Boolean(x.knockout)}))});await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 async function saveSubmission(submit){if(submit&&!submission.summary.trim()){setState('submission_summary_required');return;}setState('saving');try{await ats('saveCandidateSubmission',{applicationId:application.id,submission,submit});await load();onRefresh?.();setState('ready');if(submit)setTab('activity')}catch(e){setState(e.message||'error')}}
 const app=detail?.application||application;
 return <aside className="record-drawer screening-drawer application-closeout"><div className="drawer-head"><div><span className="page-kicker">Application 360</span><h2>{app.candidate_name||application.candidate_name}</h2><p>{app.job_title||application.job_title} · {app.stage_name||app.stage||application.stage_name||application.stage}</p></div><button onClick={onClose}>×</button></div>
 <div className="drawer-grid"><div><span>Availability</span><b>{String(app.availability||'UNKNOWN').replaceAll('_',' ')}</b></div><div><span>Notice</span><b>{app.notice_period_days!=null?`${app.notice_period_days} days`:'—'}</b></div><div><span>Expected</span><b>{app.salary_expected?`${app.salary_currency||''} ${Number(app.salary_expected).toLocaleString()}`:'—'}</b></div><div><span>Job range</span><b>{app.job_salary_min?`${app.job_currency||''} ${Number(app.job_salary_min).toLocaleString()}${app.job_salary_max?` – ${Number(app.job_salary_max).toLocaleString()}`:''}`:'—'}</b></div></div>
 <nav className="drawer-tabs" aria-label="Application sections"><button className={tab==='screening'?'active':''} onClick={()=>setTab('screening')}>Screening</button><button className={tab==='submission'?'active':''} onClick={()=>setTab('submission')}>Client submission</button><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Timeline</button></nav>
 {tab==='screening'?<section className="closeout-section"><div className="closeout-title"><div><b>Screening studio</b><small>Structured questions, score and knockout evidence stay attached to this candidate/job application.</small></div><button className="ghost-action" onClick={add}>＋ Question</button></div>{answers.length?answers.map((a,i)=><div className="screening-row" key={`${a.key}-${i}`}><input value={a.question} onChange={(e)=>update(i,'question',e.target.value)} placeholder="Question"/><textarea rows="2" value={a.answer} onChange={(e)=>update(i,'answer',e.target.value)} placeholder="Answer / evidence"/><input type="number" min="0" max="100" value={a.score} onChange={(e)=>update(i,'score',e.target.value)} placeholder="Score"/><label><input type="checkbox" checked={a.knockout} onChange={(e)=>update(i,'knockout',e.target.checked)}/> Knockout</label><button onClick={()=>setAnswers((x)=>x.filter((_,n)=>n!==i))}>Remove</button></div>):<div className="ats-empty"><b>No screening answers yet.</b><span>Add pre-screening questions and evidence for this application.</span><button className="primary-action" onClick={add}>Add first question</button></div>}<div className="drawer-actions"><button className="primary-action" onClick={saveScreening} disabled={state==='saving'}>{state==='saving'?'Saving…':'Save screening'}</button></div></section>:null}
 {tab==='submission'?<section className="closeout-section"><div className="closeout-title"><div><b>Client submission</b><small>Build one clean candidate brief without leaving the application.</small></div><span className="status-pill">{detail?.submission?.status||'DRAFT'}</span></div><label className="form-control"><span>Submission summary *</span><textarea rows="7" value={submission.summary} onChange={(e)=>setSubmission({...submission,summary:e.target.value})} placeholder="Why this candidate fits the requirement, key evidence, availability and any client-facing context."/></label><div className="form-grid two"><label className="form-control"><span>Salary expectation</span><input type="number" min="0" value={submission.salaryExpectation} onChange={(e)=>setSubmission({...submission,salaryExpectation:e.target.value})}/></label><label className="form-control"><span>Currency</span><input maxLength="3" value={submission.salaryCurrency} onChange={(e)=>setSubmission({...submission,salaryCurrency:e.target.value.toUpperCase()})}/></label><label className="form-control"><span>Availability</span><input value={submission.availability} onChange={(e)=>setSubmission({...submission,availability:e.target.value})} placeholder="Available now / date"/></label><label className="form-control"><span>Notice period (days)</span><input type="number" min="0" value={submission.noticePeriodDays} onChange={(e)=>setSubmission({...submission,noticePeriodDays:e.target.value})}/></label></div><div className="drawer-actions"><button onClick={()=>saveSubmission(false)} disabled={state==='saving'}>Save draft</button><button className="primary-action" onClick={()=>saveSubmission(true)} disabled={state==='saving'||detail?.submission?.status==='SUBMITTED'}>{detail?.submission?.status==='SUBMITTED'?'Submitted':'Submit to client'}</button></div></section>:null}
 {tab==='activity'?<section className="closeout-section"><div className="closeout-title"><div><b>Application timeline</b><small>Candidate, job and application actions in one chronological view.</small></div><span>{detail?.activity?.length||0}</span></div>{detail?.activity?.length?<div className="activity-timeline">{detail.activity.map((a)=><article key={a.id}><i/><div><b>{a.summary||String(a.action||'Activity').replaceAll('_',' ')}</b><small>{new Date(a.occurred_at).toLocaleString()}</small></div></article>)}</div>:<small>No activity recorded yet.</small>}</section>:null}
 {state==='loading'?<div className="drawer-loading">Loading application…</div>:state!=='ready'&&state!=='saving'?<div className="save-error">Application error: {state}</div>:null}</aside>
}
