'use client';

import { useEffect, useState } from 'react';

async function ats(action,payload){const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}

export default function ApplicationScreeningDrawer({application,onClose,onRefresh}){
 const[answers,setAnswers]=useState([]);const[state,setState]=useState('loading');
 async function load(){setState('loading');try{const d=await ats('scorecardContext',{applicationId:application.id});setAnswers((d.screening||[]).map((x)=>({key:x.question_key,question:x.question_text,answer:typeof x.answer==='string'?x.answer:JSON.stringify(x.answer??''),score:x.score??'',knockout:Boolean(x.knockout)})));setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[application.id]);
 function add(){setAnswers((a)=>[...a,{key:`custom_${Date.now()}`,question:'',answer:'',score:'',knockout:false}])}
 function update(i,field,value){setAnswers((a)=>a.map((x,n)=>n===i?{...x,[field]:value}:x))}
 async function save(){setState('saving');try{await ats('saveScreeningAnswers',{applicationId:application.id,answers:answers.filter((x)=>x.question.trim()).map((x)=>({key:x.key||`custom_${Math.random().toString(36).slice(2)}`,question:x.question,answer:x.answer,score:x.score===''?null:Number(x.score),knockout:Boolean(x.knockout)}))});setState('ready');onRefresh?.();await load()}catch(e){setState(e.message||'error')}}
 return <aside className="record-drawer screening-drawer"><div className="drawer-head"><div><span className="page-kicker">Application review</span><h2>{application.candidate_name}</h2><p>{application.job_title} · {application.stage_name||application.stage}</p></div><button onClick={onClose}>×</button></div><section className="closeout-section"><div className="closeout-title"><div><b>Screening studio</b><small>Structured questions, score and knockout evidence stay attached to this candidate/job application.</small></div><button className="ghost-action" onClick={add}>＋ Question</button></div>{answers.length?answers.map((a,i)=><div className="screening-row" key={`${a.key}-${i}`}><input value={a.question} onChange={(e)=>update(i,'question',e.target.value)} placeholder="Question"/><textarea rows="2" value={a.answer} onChange={(e)=>update(i,'answer',e.target.value)} placeholder="Answer / evidence"/><input type="number" min="0" max="100" value={a.score} onChange={(e)=>update(i,'score',e.target.value)} placeholder="Score"/><label><input type="checkbox" checked={a.knockout} onChange={(e)=>update(i,'knockout',e.target.checked)}/> Knockout</label><button onClick={()=>setAnswers((x)=>x.filter((_,n)=>n!==i))}>Remove</button></div>):<div className="ats-empty"><b>No screening answers yet.</b><span>Add pre-screening questions and evidence for this application.</span><button className="primary-action" onClick={add}>Add first question</button></div>}<div className="drawer-actions"><button className="primary-action" onClick={save} disabled={state==='saving'}>{state==='saving'?'Saving…':'Save screening'}</button></div></section>{state!=='ready'&&state!=='saving'&&state!=='loading'?<div className="save-error">Screening error: {state}</div>:null}</aside>
}
