'use client';

import { useEffect, useMemo, useState } from 'react';
import { qualificationChecklist, safeEvidenceText } from '@/lib/screening-domain';

const OUTCOMES=['QUALIFIED','NOT_QUALIFIED','CANDIDATE_NOT_INTERESTED','NO_RESPONSE','FOLLOW_UP_REQUIRED','ON_HOLD','WITHDRAWN'];
const SOURCES=['CANDIDATE_DECLARED','RECRUITER_VERIFIED','DOCUMENT_VERIFIED','UNKNOWN'];
const FACT_FIELDS=[
  ['relevant_experience','Relevant experience','e.g. 3.5 years production Java'],
  ['availability','Availability / notice','e.g. 30 days; available 1 Nov'],
  ['location_work_model','Location / work model','e.g. Bhopal; hybrid accepted'],
  ['compensation','Compensation / rate','Record only approved job-relevant context'],
  ['work_authorization','Work authorization','Only where relevant and authorized']
];

function key(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
async function ats(action,payload){const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({}));if(!res.ok){const e=new Error(data?.error||'request_failed');e.data=data;throw e}return data}
function list(v){return Array.isArray(v)?v:[]}
function label(v){return String(v||'UNKNOWN').replaceAll('_',' ')}

export default function ApplicationScreeningDrawer({application,onClose,onRefresh}){
 const[ctx,setCtx]=useState(null);const[state,setState]=useState('loading');const[tab,setTab]=useState('screening');const[dirty,setDirty]=useState(false);
 const[answers,setAnswers]=useState({});const[sources,setSources]=useState({});const[facts,setFacts]=useState({});const[factSources,setFactSources]=useState({});const[interest,setInterest]=useState('UNKNOWN');const[notes,setNotes]=useState('');const[recommendation,setRecommendation]=useState('');const[outcome,setOutcome]=useState('QUALIFIED');const[overrideReason,setOverrideReason]=useState('');
 const[followup,setFollowup]=useState({title:'Candidate screening follow-up',description:'',dueAt:'',priority:'NORMAL'});
 const draftKey=`xz-screening-draft:${application.id}`;
 async function load(){setState('loading');try{const d=await ats('screeningContext',{applicationId:application.id});setCtx(d);const s=d.session||{};setInterest(s.candidate_interest||'UNKNOWN');setNotes(s.recruiter_notes||'');setRecommendation(s.recruiter_recommendation||'');const a={};const src={};for(const q of d.questions||[]){a[q.question_key]=q.answer==null?'':typeof q.answer==='string'?q.answer:JSON.stringify(q.answer);src[q.question_key]=q.answer_source||'CANDIDATE_DECLARED'}setAnswers(a);setSources(src);const latest={};const latestSrc={};for(const f of d.facts||[]){if(latest[f.fact_key]===undefined){latest[f.fact_key]=f.fact_value==null?'':typeof f.fact_value==='string'?f.fact_value:JSON.stringify(f.fact_value);latestSrc[f.fact_key]=f.source_type||'UNKNOWN'}}setFacts(latest);setFactSources(latestSrc);setDirty(false);setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[application.id]);
 useEffect(()=>{if(state!=='ready'||ctx?.session)return;try{const raw=localStorage.getItem(draftKey);if(!raw)return;const d=JSON.parse(raw);setAnswers(d.answers||{});setSources(d.sources||{});setFacts(d.facts||{});setFactSources(d.factSources||{});setInterest(d.interest||'UNKNOWN');setNotes(d.notes||'');setRecommendation(d.recommendation||'')}catch{}},[state,ctx?.session?.id]);
 useEffect(()=>{if(!dirty)return;const timer=setTimeout(()=>localStorage.setItem(draftKey,JSON.stringify({answers,sources,facts,factSources,interest,notes,recommendation})),500);return()=>clearTimeout(timer)},[dirty,answers,sources,facts,factSources,interest,notes,recommendation,draftKey]);
 useEffect(()=>{const before=(e)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty]);
 const app=ctx?.application||{};const session=ctx?.session||null;const brief=session?.screening_brief||{};const questions=ctx?.questions||[];const hardStatus=String(brief.hardRuleStatus||session?.intelligence_snapshot?.hardRuleStatus||app?.matchEvidence?.hardRuleStatus||'UNKNOWN').toUpperCase();
 const answered=(k)=>String(answers[k]??'').trim()!=='';
 const checklist=useMemo(()=>qualificationChecklist({interest,hardRuleStatus:hardStatus,nonOverridable:Boolean(session?.intelligence_snapshot?.nonOverridable),mustHavesReviewed:questions.filter(q=>q.category==='MANDATORY_CONFIRMATION'&&q.question_key!=='candidate_interest').every(q=>answered(q.question_key)),mustHavesHard:questions.some(q=>q.question_key?.startsWith('must_have_')),relevantExperienceConfirmed:answered('relevant_experience')||Boolean(facts.relevant_experience),availabilityKnown:answered('availability')||Boolean(facts.availability),locationCompatible:(answered('location_work_model')||Boolean(facts.location_work_model))?true:undefined,compensationRequired:questions.some(q=>q.category==='COMPENSATION'),compensationKnown:answered('compensation')||Boolean(facts.compensation),authorizationRequired:questions.some(q=>q.category==='AUTHORIZATION'),authorizationSufficient:answered('work_authorization')||Boolean(facts.work_authorization)?true:undefined}),[interest,hardStatus,session?.intelligence_snapshot,questions,answers,facts]);
 async function start(){setState('saving');try{await ats('startScreening',{applicationId:application.id,idempotencyKey:key()});await load();onRefresh?.()}catch(e){setState(e.message||'error')}}
 async function save(){if(!session)return;setState('saving');try{const answerPayload=questions.filter(q=>String(answers[q.question_key]??'').trim()!=='').map(q=>({key:q.question_key,answer:answers[q.question_key],source:sources[q.question_key]||'CANDIDATE_DECLARED'}));const factPayload=FACT_FIELDS.filter(([k])=>String(facts[k]??'').trim()!=='').map(([k])=>({key:k,value:facts[k],source:factSources[k]||'CANDIDATE_DECLARED',verified:['RECRUITER_VERIFIED','DOCUMENT_VERIFIED'].includes(factSources[k]),evidence:'Recorded during human screening'}));await ats('saveScreeningProgress',{sessionId:session.id,expectedVersion:session.version,payload:{answers:answerPayload,facts:factPayload,candidateInterest:interest,recruiterNotes:notes,recommendation,status:session.status==='FOLLOW_UP_REQUIRED'?'FOLLOW_UP_REQUIRED':'IN_PROGRESS'},idempotencyKey:key()});localStorage.removeItem(draftKey);await load();onRefresh?.()}catch(e){if(e.data?.error==='stale_screening_version')await load();else setState(e.message||'error')}}
 async function complete(){if(!session)return;setState('saving');try{await ats('completeScreening',{sessionId:session.id,expectedVersion:session.version,outcome,override:overrideReason?{rule:'STEP4_HARD_RULE',reason:overrideReason}:null,idempotencyKey:key()});localStorage.removeItem(draftKey);await load();onRefresh?.();setTab('history')}catch(e){if(e.data?.error==='stale_screening_version')await load();else setState(e.message||'error')}}
 async function createFollowup(){if(!session)return;setState('saving');try{await ats('createScreeningFollowup',{sessionId:session.id,followup:{...followup,dueAt:followup.dueAt?new Date(followup.dueAt).toISOString():null},idempotencyKey:key()});await load();onRefresh?.();setTab('history')}catch(e){setState(e.message||'error')}}
 const active=session&&!['QUALIFIED','NOT_QUALIFIED','CANDIDATE_NOT_INTERESTED','WITHDRAWN'].includes(session.status);
 return <aside className="record-drawer screening-drawer step5-screening"><div className="drawer-head"><div><span className="page-kicker">Step 5 · Human screening</span><h2>{app.candidate?.fullName||application.candidate_name}</h2><p>{app.requirement?.title||application.job_title} · AI prepares, recruiter verifies</p></div><button onClick={onClose} aria-label="Close">×</button></div>
  {!session?<section className="screen-start"><div><b>Ready for human screening</b><p>Generate a grounded Screening Brief from the approved requirement, Step‑4 intelligence and known facts. AI will not create candidate answers or qualify the candidate.</p></div><button className="primary-action" onClick={start} disabled={state==='saving'}>{state==='saving'?'Starting…':'Start screening'}</button></section>:null}
  {session?<><nav className="drawer-tabs"><button className={tab==='screening'?'active':''} onClick={()=>setTab('screening')}>Screening</button><button className={tab==='facts'?'active':''} onClick={()=>setTab('facts')}>Verified facts</button><button className={tab==='gate'?'active':''} onClick={()=>setTab('gate')}>Qualification gate</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>History</button></nav>
  {tab==='screening'?<div className="screening-layout"><section className="screening-context"><div className="closeout-title"><div><b>Screening Brief</b><small>Read this in under 30 seconds before contacting the candidate.</small></div><span className={`status-pill ${hardStatus==='FAIL'?'danger':''}`}>{hardStatus}</span></div><div className="brief-grid"><Brief title="Why relevant" items={brief.whyRelevant}/><Brief title="Important gaps" items={brief.gaps}/><Brief title="Still unknown" items={brief.unknowns}/><Brief title="Inconsistencies" items={brief.inconsistencies}/><Brief title="Attention" items={brief.attention}/><Brief title="Potential blockers" items={brief.blockers}/></div><div className="provenance-banner">{brief.provenanceRule||'AI suggestions are not candidate answers. Human/document evidence is required for verified facts.'}</div></section>
   <section className="screening-work"><div className="closeout-title"><div><b>Human call workspace</b><small>Ask only job-relevant questions. Record what the candidate actually said.</small></div><span>{questions.length} questions</span></div><label className="form-control"><span>Candidate interest *</span><select value={interest} onChange={e=>{setInterest(e.target.value);setDirty(true)}}><option>UNKNOWN</option><option>INTERESTED</option><option>NOT_INTERESTED</option><option>UNSURE</option></select></label>{questions.map(q=><article className="screen-question" key={q.id||q.question_key}><header><div><span>{label(q.category)}</span><b>{q.question_text}</b></div><em>{q.priority||'MEDIUM'}</em></header><p>{q.reason||'Grounded in approved requirement / candidate gaps.'}</p><div className="screen-answer"><textarea rows="2" value={answers[q.question_key]??''} onChange={e=>{setAnswers({...answers,[q.question_key]:e.target.value});setDirty(true)}} placeholder="Record candidate answer / evidence — do not infer"/><select value={sources[q.question_key]||'CANDIDATE_DECLARED'} onChange={e=>{setSources({...sources,[q.question_key]:e.target.value});setDirty(true)}}>{SOURCES.map(s=><option key={s}>{s}</option>)}</select></div></article>)}<label className="form-control"><span>Recruiter notes</span><textarea rows="4" value={notes} onChange={e=>{setNotes(e.target.value);setDirty(true)}} placeholder="Professional, job-relevant notes only"/></label><label className="form-control"><span>Recruiter recommendation</span><textarea rows="2" value={recommendation} onChange={e=>{setRecommendation(e.target.value);setDirty(true)}} placeholder="Human recommendation; AI does not qualify or reject"/></label><div className="drawer-actions"><span>{dirty?'Unsaved changes':'Saved'}</span><button className="primary-action" disabled={!active||state==='saving'} onClick={save}>{state==='saving'?'Saving…':'Save screening'}</button></div></section></div>:null}
  {tab==='facts'?<section className="closeout-section"><div className="closeout-title"><div><b>Verified facts</b><small>Conflicting values remain visible; history is never silently rewritten.</small></div><span>{ctx.facts?.length||0} assertions</span></div><div className="fact-editor">{FACT_FIELDS.map(([k,t,p])=><article key={k}><label className="form-control"><span>{t}</span><input value={facts[k]??''} onChange={e=>{setFacts({...facts,[k]:e.target.value});setDirty(true)}} placeholder={p}/></label><label className="form-control"><span>Source</span><select value={factSources[k]||'CANDIDATE_DECLARED'} onChange={e=>{setFactSources({...factSources,[k]:e.target.value});setDirty(true)}}>{SOURCES.map(s=><option key={s}>{s}</option>)}</select></label></article>)}</div><div className="fact-history">{list(ctx.facts).map(f=><div key={f.id}><b>{label(f.fact_key)}</b><span>{typeof f.fact_value==='string'?f.fact_value:JSON.stringify(f.fact_value)}</span><small>{f.source_type}{f.verified?' · VERIFIED':''} · {new Date(f.created_at).toLocaleString()}</small></div>)}</div><div className="drawer-actions"><button className="primary-action" disabled={!active||state==='saving'} onClick={save}>Save facts</button></div></section>:null}
  {tab==='gate'?<section className="closeout-section"><div className="closeout-title"><div><b>Qualification gate</b><small>Human recruiter decides. Missing non-hard information warns; approved non-overridable hard rules still block.</small></div><span className={`status-pill ${checklist.canQualify?'':'warning'}`}>{checklist.canQualify?'READY':'REVIEW'}</span></div><div className="qualification-checks">{checklist.checks.map(c=><div key={c.key}><span>{c.state==='PASS'?'✓':c.state==='FAIL'?'×':'?'}</span><div><b>{c.label}</b><small>{c.hard?'Hard gate':'Warning when incomplete'} · {c.state}</small></div></div>)}</div><div className="form-grid two"><label className="form-control"><span>Screening outcome</span><select value={outcome} onChange={e=>setOutcome(e.target.value)}>{OUTCOMES.map(o=><option key={o}>{o}</option>)}</select></label>{outcome==='QUALIFIED'&&['WARN','FAIL'].includes(hardStatus)?<label className="form-control"><span>Override reason *</span><input value={overrideReason} onChange={e=>setOverrideReason(e.target.value)} placeholder="Required for permitted WARN/FAIL override"/></label>:null}</div><div className="drawer-actions"><span>Qualification is always a human action.</span><button className="primary-action" disabled={!active||state==='saving'||(outcome==='QUALIFIED'&&!checklist.canQualify)} onClick={complete}>Complete screening</button></div><hr/><div className="closeout-title"><div><b>Follow-up</b><small>Reuses the existing task system; no duplicate follow-up engine.</small></div></div><div className="form-grid two"><label className="form-control"><span>Follow-up title</span><input value={followup.title} onChange={e=>setFollowup({...followup,title:e.target.value})}/></label><label className="form-control"><span>Due</span><input type="datetime-local" value={followup.dueAt} onChange={e=>setFollowup({...followup,dueAt:e.target.value})}/></label><label className="form-control wide"><span>Reason/context</span><textarea rows="2" value={followup.description} onChange={e=>setFollowup({...followup,description:e.target.value})}/></label></div><button onClick={createFollowup} disabled={!active||state==='saving'}>Create Follow-up</button></section>:null}
  {tab==='history'?<section className="closeout-section"><div className="closeout-title"><div><b>Screening history</b><small>Previous sessions, summaries, facts and audit events remain preserved.</small></div><span>{ctx.activity?.length||0}</span></div>{list(ctx.summaries).map(s=><article className="summary-card" key={s.id}><header><b>{s.outcome}</b><span>v{s.version_number}</span></header><p>{s.summary_data?.recruiterRecommendation||s.summary_data?.recruiterNotes||'Structured screening summary recorded.'}</p><small>{new Date(s.created_at).toLocaleString()}</small></article>)}{list(ctx.followups).map(t=><article className="summary-card" key={t.id}><header><b>Follow-up · {t.status}</b><span>{t.priority}</span></header><p>{t.title}</p><small>{t.due_at?new Date(t.due_at).toLocaleString():'No due date'}</small></article>)}<div className="activity-timeline">{list(ctx.activity).map(a=><article key={a.id}><i/><div><b>{a.summary||label(a.action)}</b><small>{new Date(a.occurred_at).toLocaleString()}</small></div></article>)}</div></section>:null}</>:null}
  {state==='loading'?<div className="drawer-loading">Loading screening context…</div>:state!=='ready'&&state!=='saving'?<div className="save-error">Screening error: {label(state)}</div>:null}
 </aside>
}

function Brief({title,items}){const rows=list(items);return <div className="brief-card"><span>{title}</span>{rows.length?<ul>{rows.map((x,i)=><li key={i}>{safeEvidenceText(typeof x==='string'?x:JSON.stringify(x))}</li>)}</ul>:<small>None recorded</small>}</div>}
