'use client';

import { useEffect, useRef, useState } from 'react';

export default function AttachmentPanel({entityType,entityId,title='Attachments'}){
 const[items,setItems]=useState([]);const[state,setState]=useState('loading');const[file,setFile]=useState(null);const inputRef=useRef(null);
 async function load(){if(!entityId)return;setState('loading');const res=await fetch(`/api/ats/attachment?entityType=${encodeURIComponent(entityType)}&entityId=${encodeURIComponent(entityId)}`,{cache:'no-store'});const data=await res.json().catch(()=>({}));if(!res.ok){setState(data.error||'error');return}setItems(data.attachments||[]);setState('ready')}
 useEffect(()=>{load()},[entityType,entityId]);
 async function upload(){if(!file)return;setState('uploading');const fd=new FormData();fd.append('entityType',entityType);fd.append('entityId',entityId);fd.append('file',file);const res=await fetch('/api/ats/attachment',{method:'POST',body:fd});const data=await res.json().catch(()=>({}));if(!res.ok){setState(data.error||'error');return}setFile(null);if(inputRef.current)inputRef.current.value='';await load()}
 async function archive(id){if(!confirm('Archive this attachment?'))return;setState('saving');const res=await fetch('/api/ats/attachment',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({attachmentId:id})});const data=await res.json().catch(()=>({}));if(!res.ok){setState(data.error||'error');return}await load()}
 return <section className="closeout-section attachment-panel"><div className="closeout-title"><div><b>{title}</b><small>Private workspace files · signed access · PDF/DOCX/TXT/PNG/JPEG · max 8 MB</small></div><span>{items.length}</span></div><div className="resume-upload-row"><input ref={inputRef} type="file" accept=".pdf,.docx,.txt,.png,.jpg,.jpeg,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,image/png,image/jpeg" onChange={(e)=>setFile(e.target.files?.[0]||null)}/><button className="primary-action" disabled={!file||state==='uploading'} onClick={upload}>{state==='uploading'?'Uploading…':'Upload file'}</button></div>{items.length?<div className="document-list">{items.map((a)=><article key={a.id}><div><b>{a.filename}</b><small>{a.mime_type||'File'}{a.size_bytes?` · ${Math.max(1,Math.round(a.size_bytes/1024))} KB`:''} · {new Date(a.created_at).toLocaleString()}</small></div><div className="attachment-actions"><button onClick={()=>window.open(`/api/ats/attachment?attachmentId=${encodeURIComponent(a.id)}`,'_blank','noopener,noreferrer')}>Open</button><button className="danger-action" onClick={()=>archive(a.id)}>Archive</button></div></article>)}</div>:state==='ready'?<small>No files attached yet.</small>:null}{!['ready','loading','uploading','saving'].includes(state)?<small className="save-error">Attachment error: {state}</small>:null}</section>
}
