'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import CrmDetailDrawer from '@/app/components/CrmDetailDrawer';

async function crm(action,payload){const res=await fetch('/api/crm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}
const money=(v,c)=>v==null?'—':`${c||''} ${Number(v).toLocaleString()}`.trim();

export default function BusinessPipelineWorkspace({context,reference}){
 const router=useRouter();const[view,setView]=useState('board');const[selected,setSelected]=useState(null);const[state,setState]=useState('idle');const stages=context?.stages||[];const opportunities=context?.opportunities||[];const summary=context?.summary||{};
 const grouped=useMemo(()=>Object.fromEntries(stages.map(s=>[s.id,opportunities.filter(o=>o.stage_id===s.id)])),[stages,opportunities]);
 async function move(opportunity,stage){if(opportunity.stage_id===stage.id)return;let reason='';if(['LOST','DISQUALIFIED'].includes(stage.code)){reason=prompt(`Reason required to move to ${stage.name}`)||'';if(!reason.trim())return;}setState('saving');try{await crm('moveOpportunity',{opportunityId:opportunity.id,stageId:stage.id,reason});router.refresh();setState('saved')}catch(e){setState(e.message||'error')}}
 function dragStart(e,o){e.dataTransfer.setData('text/xz-opportunity',o.id);e.dataTransfer.effectAllowed='move'}
 async function drop(e,stage){e.preventDefault();const id=e.dataTransfer.getData('text/xz-opportunity');const o=opportunities.find(x=>x.id===id);if(o)await move(o,stage)}
 return <div className="business-pipeline-workspace"><div className="crm-summary-cards pipeline-summary"><div><span>Total opportunities</span><b>{summary.total||0}</b></div><div><span>Open pipeline</span><b>{Number(summary.open_value||0).toLocaleString()}</b></div><div><span>Weighted pipeline</span><b>{Number(summary.weighted_value||0).toLocaleString()}</b></div><div><span>Won value</span><b>{Number(summary.won_value||0).toLocaleString()}</b></div></div><div className="pipeline-viewbar"><div><button className={view==='board'?'active':''} onClick={()=>setView('board')}>Board</button><button className={view==='table'?'active':''} onClick={()=>setView('table')}>Table</button></div><span>{state==='saving'?'Saving stage…':state==='saved'?'Stage saved':''}</span><button className="primary-action" onClick={()=>router.push('/opportunities?action=create')}>＋ Opportunity</button></div>
 {view==='board'?<div className="bd-board" aria-label="Business development pipeline">{stages.map(stage=><section key={stage.id} className={`bd-column semantic-${String(stage.semantic||'NEUTRAL').toLowerCase()}`} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,stage)}><header><div><b>{stage.name}</b><small>{grouped[stage.id]?.length||0} records</small></div><span>{money((grouped[stage.id]||[]).reduce((n,o)=>n+Number(o.weighted_value||0),0),'')}</span></header><div className="bd-cards">{(grouped[stage.id]||[]).map(o=><article key={o.id} draggable onDragStart={e=>dragStart(e,o)} onClick={()=>setSelected(o)}><div className="bd-card-head"><b>{o.name}</b><span>{o.probability}%</span></div><strong>{o.client_name}</strong><div className="bd-value"><b>{money(o.estimated_value,o.currency_code)}</b><small>Weighted {money(o.weighted_value,o.currency_code)}</small></div><div className="bd-next"><span>Next</span><p>{o.next_action||'No next action set'}</p></div><footer><small>{o.owner_name||'Unassigned'}</small><small>{o.expected_close_date||'No close date'}</small></footer></article>)}</div></section>)}</div>:<div className="ats-table-wrap"><table className="ats-table"><thead><tr><th>Opportunity</th><th>Account</th><th>Stage</th><th>Value</th><th>Probability</th><th>Weighted</th><th>Owner</th><th>Next action</th></tr></thead><tbody>{opportunities.map(o=><tr key={o.id} onClick={()=>setSelected(o)}><td><b>{o.name}</b><small>{o.opportunity_type?.replaceAll('_',' ')}</small></td><td>{o.client_name}</td><td><select value={o.stage_id} onClick={e=>e.stopPropagation()} onChange={e=>{const s=stages.find(x=>x.id===e.target.value);if(s)move(o,s)}}>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></td><td>{money(o.estimated_value,o.currency_code)}</td><td>{o.probability}%</td><td>{money(o.weighted_value,o.currency_code)}</td><td>{o.owner_name||'—'}</td><td>{o.next_action||'—'}</td></tr>)}</tbody></table>{!opportunities.length?<div className="ats-empty"><b>No business opportunities yet.</b><span>Create an opportunity from an account or the Opportunities page.</span></div>:null}</div>}
 {selected?<CrmDetailDrawer type="OPPORTUNITY" row={selected} reference={reference} onClose={()=>setSelected(null)} onEdit={()=>router.push(`/opportunities?q=${encodeURIComponent(selected.name)}`)} onRefresh={()=>router.refresh()}/>:null}</div>
}
