'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

const PARSE_FIELDS = [
  ['fullName','Name'],['email','Email'],['phone','Phone'],['headline','Headline'],['currentTitle','Current title'],['experienceYears','Experience'],['skills','Skills'],['education','Education']
];

async function ats(action,payload){
  const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});
  const data=await res.json().catch(()=>({error:'invalid_response'}));
  if(!res.ok) throw new Error(data?.error||'request_failed');
  return data;
}

export default function CandidateCloseoutDrawer({candidate,onClose,onEdit,onAddToJob,onPortal,onArchive,onRefresh}){
 const [detail,setDetail]=useState(null);const[state,setState]=useState('loading');const[uploadState,setUploadState]=useState('idle');const[file,setFile]=useState(null);const[reviewFields,setReviewFields]=useState({});const inputRef=useRef(null);
 const latestRun=useMemo(()=>detail?.parse_runs?.find((r)=>r.status==='COMPLETED'&&r.review_state!=='ACCEPTED')||detail?.parse_runs?.[0]||null,[detail]);
 async function load(){if(!candidate?.id)return;setState('loading');try{setDetail(await ats('candidateCloseout',{candidateId:candidate.id}));setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[candidate?.id]);
 useEffect(()=>{if(!latestRun?.extracted_data){setReviewFields({});return;}const next={};for(const[key]of PARSE_FIELDS){if(latestRun.extracted_data[key]!=null&&(latestRun.field_confidence?.[key]||0)>=0.5)next[key]=true;}setReviewFields(next)},[latestRun?.id]);
 async function upload(){if(!file)return;setUploadState('uploading');const form=new FormData();form.append('candidateId',candidate.id);form.append('file',file);const res=await fetch('/api/ats/resume',{method:'POST',body:form});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok){setUploadState(data.error||'error');return;}setUploadState('parsed');setFile(null);if(inputRef.current)inputRef.current.value='';await load();onRefresh?.()}
 async function applyParse(){if(!latestRun?.id)return;setState('saving');try{await ats('applyResumeParse',{parseRunId:latestRun.id,fields:reviewFields});await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 async function merge(duplicate){if(!confirm(`Merge ${duplicate.full_name} into ${candidate.full_name}? The duplicate profile will be archived and recruitment history preserved.`))return;setState('saving');try{await ats('mergeCandidates',{survivorId:candidate.id,duplicateId:duplicate.id,resolution:{}});await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 async function pool(pool){setState('saving');try{await ats('talentPoolMembership',{candidateId:candidate.id,poolId:pool.id,add:!pool.member});await load();setState('ready')}catch(e){setState(e.message||'error')}}
 return <aside className="record-drawer candidate-closeout-drawer" aria-label="Candidate 360"><div className="drawer-head"><div><span className="page-kicker">Candidate 360</span><h2>{candidate.full_name}</h2><p>{candidate.current_title||'Candidate'}{candidate.current_company?` · ${candidate.current_company}`:''}</p></div><button onClick={onClose}>×</button></div>
 <div className="drawer-grid"><div><span>Email</span><b>{candidate.email||'—'}</b></div><div><span>Phone</span><b>{candidate.phone||'—'}</b></div><div><span>Location</span><b>{[candidate.city,candidate.region,candidate.country_code].filter(Boolean).join(', ')||'—'}</b></div><div><span>Timezone</span><b>{candidate.timezone||'—'}</b></div><div><span>Experience</span><b>{candidate.experience_years??'—'} years</b></div><div><span>Notice</span><b>{candidate.notice_period_days!=null?`${candidate.notice_period_days} days`:'—'}</b></div></div>
 <div className="drawer-actions"><button className="primary-action" onClick={onEdit}>Edit profile</button><button onClick={onAddToJob}>Add to job</button><button onClick={onPortal}>Create portal link</button><button className="danger-action" onClick={onArchive}>Archive</button></div>
 <section className="closeout-section"><div className="closeout-title"><div><b>Resume intelligence</b><small>PDF, DOCX or TXT · max 8 MB · private storage</small></div><span>{detail?.documents?.length||0} files</span></div><div className="resume-upload-row"><input ref={inputRef} type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={(e)=>setFile(e.target.files?.[0]||null)}/><button className="primary-action" disabled={!file||uploadState==='uploading'} onClick={upload}>{uploadState==='uploading'?'Parsing…':'Upload & parse'}</button></div>{uploadState!=='idle'&&uploadState!=='uploading'&&uploadState!=='parsed'?<small className="save-error">Resume failed: {uploadState}</small>:null}{uploadState==='parsed'?<small className="save-good">Resume parsed. Review extracted fields before applying.</small>:null}
 {latestRun?.status==='COMPLETED'&&latestRun?.review_state!=='ACCEPTED'?<div className="parse-review"><div className="parse-review-head"><b>Review extracted fields</b><span>{latestRun.parser_version}</span></div>{PARSE_FIELDS.map(([key,label])=>{const value=latestRun.extracted_data?.[key];if(value==null||value===''||(Array.isArray(value)&&!value.length))return null;const conf=Math.round(Number(latestRun.field_confidence?.[key]||0)*100);return <label key={key} className="parse-field"><input type="checkbox" checked={Boolean(reviewFields[key])} onChange={(e)=>setReviewFields({...reviewFields,[key]:e.target.checked})}/><span><b>{label}</b><small>{Array.isArray(value)?value.map((v)=>typeof v==='string'?v:v?.text).filter(Boolean).join(' · '):String(value)}</small></span><em>{conf}%</em></label>})}<button className="primary-action" onClick={applyParse} disabled={state==='saving'||!Object.values(reviewFields).some(Boolean)}>Apply selected fields</button></div>:null}
 {latestRun?.status==='FAILED'?<div className="save-error">Latest resume parse failed: {latestRun.error_message||'Unknown parser error'}</div>:null}</section>
 <section className="closeout-section"><div className="closeout-title"><div><b>Duplicate review</b><small>Email, phone and exact-name signals</small></div><span>{detail?.duplicates?.length||0} possible</span></div>{detail?.duplicates?.length?<div className="duplicate-list">{detail.duplicates.map((d)=><article key={d.id}><div><b>{d.full_name}</b><small>{d.email||d.phone||'No contact'} · {d.current_title||'No title'}</small></div><span>{d.score}%</span><button onClick={()=>merge(d)}>Compare & merge</button></article>)}</div>:<small>No likely duplicate profiles found.</small>}</section>
 <section className="closeout-section"><div className="closeout-title"><div><b>Talent pools</b><small>Manual pool membership</small></div></div>{detail?.talent_pools?.length?<div className="pool-list">{detail.talent_pools.map((p)=><button key={p.id} className={p.member?'active':''} onClick={()=>pool(p)}>{p.member?'✓ ':''}{p.name}</button>)}</div>:<small>No active talent pools configured yet.</small>}</section>
 {state==='loading'?<div className="drawer-loading">Loading Candidate 360…</div>:state!=='ready'&&state!=='saving'?<div className="save-error">Candidate 360 error: {state}</div>:null}</aside>
}
