'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

const PARSE_FIELDS = [
  ['fullName','Name'],['email','Email'],['phone','Phone'],['headline','Headline'],['currentTitle','Current title'],['experienceYears','Experience'],['skills','Skills'],['education','Education']
];
const DEFAULT_RESOLUTION={primaryEmail:'keep',primaryPhone:'keep',currentTitle:'keep',currentCompany:'keep',city:'keep',countryCode:'keep'};

async function ats(action,payload){
  const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});
  const data=await res.json().catch(()=>({error:'invalid_response'}));
  if(!res.ok) throw new Error(data?.error||'request_failed');
  return data;
}

function activityLabel(a){
  const raw=a?.summary||a?.action||'Activity';
  return String(raw).replaceAll('_',' ');
}
function display(value,fallback='—'){return value==null||value===''?fallback:String(value)}

export default function CandidateCloseoutDrawer({candidate,onClose,onEdit,onAddToJob,onPortal,onArchive,onRefresh}){
 const [detail,setDetail]=useState(null);const[state,setState]=useState('loading');const[uploadState,setUploadState]=useState('idle');const[file,setFile]=useState(null);const[reviewFields,setReviewFields]=useState({});const[compareCandidate,setCompareCandidate]=useState(null);const[mergeResolution,setMergeResolution]=useState(DEFAULT_RESOLUTION);const inputRef=useRef(null);
 const latestRun=useMemo(()=>detail?.parse_runs?.find((r)=>r.status==='COMPLETED'&&r.review_state!=='ACCEPTED')||detail?.parse_runs?.[0]||null,[detail]);
 async function load(){if(!candidate?.id)return;setState('loading');try{setDetail(await ats('candidateCloseout',{candidateId:candidate.id}));setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[candidate?.id]);
 useEffect(()=>{if(!latestRun?.extracted_data){setReviewFields({});return;}const next={};for(const[key]of PARSE_FIELDS){if(latestRun.extracted_data[key]!=null&&(latestRun.field_confidence?.[key]||0)>=0.5)next[key]=true;}setReviewFields(next)},[latestRun?.id]);
 async function upload(){if(!file)return;setUploadState('uploading');const form=new FormData();form.append('candidateId',candidate.id);form.append('file',file);const res=await fetch('/api/ats/resume',{method:'POST',body:form});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok){setUploadState(data.error||'error');return;}setUploadState('parsed');setFile(null);if(inputRef.current)inputRef.current.value='';await load();onRefresh?.()}
 async function applyParse(){if(!latestRun?.id)return;setState('saving');try{await ats('applyResumeParse',{parseRunId:latestRun.id,fields:reviewFields});await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 async function merge(duplicate){if(!confirm(`Merge ${duplicate.full_name} into ${candidate.full_name}? The duplicate profile will be archived, selected primary values applied, and recruitment history preserved.`))return;setState('saving');try{await ats('mergeCandidates',{survivorId:candidate.id,duplicateId:duplicate.id,resolution:mergeResolution});setCompareCandidate(null);setMergeResolution(DEFAULT_RESOLUTION);await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 async function pool(pool){setState('saving');try{await ats('talentPoolMembership',{candidateId:candidate.id,poolId:pool.id,add:!pool.member});await load();setState('ready')}catch(e){setState(e.message||'error')}}
 async function createPool(){const name=prompt('Talent pool name');if(!name?.trim())return;const description=prompt('Optional description')||'';setState('saving');try{const created=await ats('createTalentPool',{name:name.trim(),description});await ats('talentPoolMembership',{candidateId:candidate.id,poolId:created.id,add:true});await load();setState('ready')}catch(e){setState(e.message||'error')}}
 function openDocument(documentId){window.open(`/api/ats/document?documentId=${encodeURIComponent(documentId)}`,'_blank','noopener,noreferrer')}
 function startCompare(d){setCompareCandidate(d);setMergeResolution({...DEFAULT_RESOLUTION})}
 function resolutionRow(key,label,keepValue,duplicateValue){if(display(keepValue)===display(duplicateValue))return null;const choice=mergeResolution[key]||'keep';return <div className="merge-resolution-row" key={key}><span>{label}</span><button className={choice==='keep'?'active':''} onClick={()=>setMergeResolution({...mergeResolution,[key]:'keep'})}><small>Keep</small><b>{display(keepValue)}</b></button><button className={choice==='duplicate'?'active':''} onClick={()=>setMergeResolution({...mergeResolution,[key]:'duplicate'})}><small>Use duplicate</small><b>{display(duplicateValue)}</b></button></div>}
 return <aside className="record-drawer candidate-closeout-drawer" aria-label="Candidate 360"><div className="drawer-head"><div><span className="page-kicker">Candidate 360</span><h2>{candidate.full_name}</h2><p>{candidate.current_title||'Candidate'}{candidate.current_company?` · ${candidate.current_company}`:''}</p></div><button onClick={onClose}>×</button></div>
 <div className="drawer-grid"><div><span>Email</span><b>{candidate.email||'—'}</b></div><div><span>Phone</span><b>{candidate.phone||'—'}</b></div><div><span>Location</span><b>{[candidate.city,candidate.region,candidate.country_code].filter(Boolean).join(', ')||'—'}</b></div><div><span>Timezone</span><b>{candidate.timezone||'—'}</b></div><div><span>Experience</span><b>{candidate.experience_years??'—'} years</b></div><div><span>Notice</span><b>{candidate.notice_period_days!=null?`${candidate.notice_period_days} days`:'—'}</b></div></div>
 <div className="drawer-actions"><a className="primary-action drawer-link-action" href={`/candidates/${candidate.id}`}>Full profile</a><button onClick={onEdit}>Quick edit</button><button onClick={onAddToJob}>Add to job</button><button onClick={onPortal}>Create portal link</button><button className="danger-action" onClick={onArchive}>Archive</button></div>
 <section className="closeout-section"><div className="closeout-title"><div><b>Resume intelligence</b><small>PDF, DOCX or TXT · max 8 MB · private storage</small></div><span>{detail?.documents?.length||0} files</span></div><div className="resume-upload-row"><input ref={inputRef} type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={(e)=>setFile(e.target.files?.[0]||null)}/><button className="primary-action" disabled={!file||uploadState==='uploading'} onClick={upload}>{uploadState==='uploading'?'Parsing…':'Upload & parse'}</button></div>{uploadState!=='idle'&&uploadState!=='uploading'&&uploadState!=='parsed'?<small className="save-error">Resume failed: {uploadState}</small>:null}{uploadState==='parsed'?<small className="save-good">Resume parsed. Review extracted fields before applying.</small>:null}
 {detail?.documents?.length?<div className="document-list">{detail.documents.map((d)=><article key={d.id}><div><b>{d.filename}</b><small>Resume v{d.version_number}{d.is_primary?' · Primary':''}{d.from_merged_profile?' · merged history':''}</small></div><button onClick={()=>openDocument(d.id)}>Open securely</button></article>)}</div>:null}
 {latestRun?.status==='COMPLETED'&&latestRun?.review_state!=='ACCEPTED'?<div className="parse-review"><div className="parse-review-head"><b>Review extracted fields</b><span>{latestRun.parser_version}</span></div>{PARSE_FIELDS.map(([key,label])=>{const value=latestRun.extracted_data?.[key];if(value==null||value===''||(Array.isArray(value)&&!value.length))return null;const conf=Math.round(Number(latestRun.field_confidence?.[key]||0)*100);return <label key={key} className="parse-field"><input type="checkbox" checked={Boolean(reviewFields[key])} onChange={(e)=>setReviewFields({...reviewFields,[key]:e.target.checked})}/><span><b>{label}</b><small>{Array.isArray(value)?value.map((v)=>typeof v==='string'?v:v?.text).filter(Boolean).join(' · '):String(value)}</small></span><em>{conf}%</em></label>})}<button className="primary-action" onClick={applyParse} disabled={state==='saving'||!Object.values(reviewFields).some(Boolean)}>Apply selected fields</button></div>:null}
 {latestRun?.status==='FAILED'?<div className="save-error">Latest resume parse failed: {latestRun.error_message||'Unknown parser error'}</div>:null}</section>
 <section className="closeout-section"><div className="closeout-title"><div><b>Duplicate review</b><small>Email, phone and exact-name signals · never auto-merged</small></div><span>{detail?.duplicates?.length||0} possible</span></div>{detail?.duplicates?.length?<div className="duplicate-list">{detail.duplicates.map((d)=><article key={d.id}><div><b>{d.full_name}</b><small>{d.email||d.phone||'No contact'} · {d.current_title||'No title'}</small></div><span>{d.score}%</span><button onClick={()=>startCompare(d)}>Compare</button></article>)}</div>:<small>No likely duplicate profiles found.</small>}{compareCandidate?<div className="duplicate-compare"><div className="compare-grid"><article><span>Surviving profile</span><b>{candidate.full_name}</b><small>{candidate.email||'No email'}</small><small>{candidate.phone||'No phone'}</small><small>{candidate.current_title||'No title'}</small><small>{candidate.current_company||'No company'}</small></article><article><span>Duplicate profile</span><b>{compareCandidate.full_name}</b><small>{compareCandidate.email||'No email'}</small><small>{compareCandidate.phone||'No phone'}</small><small>{compareCandidate.current_title||'No title'}</small><small>{compareCandidate.current_company||'No company'}</small></article></div><div className="merge-resolution"><b>Choose primary values</b><small>Skills, languages, certifications and tags are unioned automatically. Alternate email/phone history is retained.</small>{resolutionRow('primaryEmail','Primary email',candidate.email,compareCandidate.email)}{resolutionRow('primaryPhone','Primary phone',candidate.phone,compareCandidate.phone)}{resolutionRow('currentTitle','Current title',candidate.current_title,compareCandidate.current_title)}{resolutionRow('currentCompany','Current company',candidate.current_company,compareCandidate.current_company)}{resolutionRow('city','City',candidate.city,compareCandidate.city)}{resolutionRow('countryCode','Country',candidate.country_code,compareCandidate.country_code)}</div><div className="drawer-actions"><button onClick={()=>{setCompareCandidate(null);setMergeResolution(DEFAULT_RESOLUTION)}}>Cancel</button><button className="danger-action" onClick={()=>merge(compareCandidate)}>Merge with selected values</button></div></div>:null}{detail?.merge_history?.length?<div className="merge-history"><b>Previous merges</b>{detail.merge_history.map((m)=><small key={m.id}>{m.merged_candidate_name||'Archived profile'} merged {new Date(m.created_at).toLocaleString()}</small>)}</div>:null}</section>
 <section className="closeout-section"><div className="closeout-title"><div><b>Talent pools</b><small>Reusable candidate groups for fast sourcing</small></div><button className="ghost-action" onClick={createPool}>＋ Pool</button></div>{detail?.talent_pools?.length?<div className="pool-list">{detail.talent_pools.map((p)=><button key={p.id} className={p.member?'active':''} onClick={()=>pool(p)}>{p.member?'✓ ':''}{p.name}</button>)}</div>:<div className="ats-empty"><span>No active talent pools configured yet.</span><button onClick={createPool}>Create first pool</button></div>}</section>
 <section className="closeout-section"><div className="closeout-title"><div><b>Activity timeline</b><small>Recruitment actions remain auditable after refresh and duplicate merges.</small></div><span>{detail?.activity?.length||0}</span></div>{detail?.activity?.length?<div className="activity-timeline">{detail.activity.map((a)=><article key={a.id}><i aria-hidden="true"/><div><b>{activityLabel(a)}</b><small>{new Date(a.occurred_at).toLocaleString()}</small></div></article>)}</div>:<small>No recorded candidate activity yet.</small>}</section>
 {state==='loading'?<div className="drawer-loading">Loading Candidate 360…</div>:state!=='ready'&&state!=='saving'?<div className="save-error">Candidate 360 error: {state}</div>:null}</aside>
}
