'use client';

import { useRef, useState } from 'react';

export default function CandidatePortalProfile({token,candidate}){
 const[form,setForm]=useState({preferredName:candidate.preferred_name||'',email:candidate.email||'',phone:candidate.phone||'',city:candidate.city||'',region:candidate.region||'',availabilityStatus:candidate.availability_status||'UNKNOWN',workplacePreference:candidate.workplace_preference||'',consentStatus:candidate.consent_status==='WITHDRAWN'?'WITHDRAWN':'GRANTED'});const[state,setState]=useState('idle');const[file,setFile]=useState(null);const[resumeState,setResumeState]=useState('idle');const fileRef=useRef(null);
 async function save(){setState('saving');const res=await fetch('/api/public/candidate-portal',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,patch:form})});const data=await res.json().catch(()=>({}));if(!res.ok){setState(data.error||'error');return}setState('saved')}
 async function uploadResume(){if(!file)return;setResumeState('uploading');const fd=new FormData();fd.append('token',token);fd.append('file',file);const res=await fetch('/api/public/candidate-portal/resume',{method:'POST',body:fd});const data=await res.json().catch(()=>({}));if(!res.ok){setResumeState(data.error||'error');return}setResumeState('saved');setFile(null);if(fileRef.current)fileRef.current.value=''}
 return <section className="portal-profile-panel"><div><span className="page-kicker">Your profile</span><h2>Keep recruitment details current</h2><p>Changes are written only to your secure candidate profile. You can also withdraw recruitment consent or upload a newer CV/resume.</p></div><div className="form-grid two"><label className="form-control"><span>Preferred name</span><input value={form.preferredName} onChange={(e)=>setForm({...form,preferredName:e.target.value})}/></label><label className="form-control"><span>Email</span><input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span>Phone</span><input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span>City</span><input value={form.city} onChange={(e)=>setForm({...form,city:e.target.value})}/></label><label className="form-control"><span>Region / state</span><input value={form.region} onChange={(e)=>setForm({...form,region:e.target.value})}/></label><label className="form-control"><span>Availability</span><select value={form.availabilityStatus} onChange={(e)=>setForm({...form,availabilityStatus:e.target.value})}>{['UNKNOWN','AVAILABLE_NOW','AVAILABLE_SOON','PASSIVE','NOT_AVAILABLE'].map((v)=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Workplace preference</span><select value={form.workplacePreference} onChange={(e)=>setForm({...form,workplacePreference:e.target.value})}><option value="">Unspecified</option>{['ONSITE','HYBRID','REMOTE','FLEXIBLE'].map((v)=><option key={v}>{v}</option>)}</select></label><label className="form-control"><span>Recruitment consent</span><select value={form.consentStatus} onChange={(e)=>setForm({...form,consentStatus:e.target.value})}><option value="GRANTED">Granted</option><option value="WITHDRAWN">Withdrawn</option></select></label></div><div className="portal-profile-actions"><span>{state==='saving'?'Saving…':state==='saved'?'Profile updated.':state!=='idle'?`Could not update: ${state}`:''}</span><button className="primary-action" disabled={state==='saving'} onClick={save}>Save profile</button></div>
 <div className="portal-resume-panel"><div><b>Update CV / Resume</b><small>PDF, DOCX or TXT · maximum 8 MB · stored privately. Parsed fields are reviewed by the recruiter before changing your verified profile.</small></div><div className="resume-upload-row"><input ref={fileRef} type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={(e)=>setFile(e.target.files?.[0]||null)}/><button className="primary-action" disabled={!file||resumeState==='uploading'} onClick={uploadResume}>{resumeState==='uploading'?'Uploading…':'Upload resume'}</button></div>{resumeState==='saved'?<small className="save-good">New resume uploaded securely. Your recruiter will review extracted fields.</small>:resumeState!=='idle'&&resumeState!=='uploading'?<small className="save-error">Resume upload failed: {resumeState}</small>:null}</div>
 </section>
}
