'use client';

import { useEffect, useState } from 'react';
import NotesPanel from '@/app/components/NotesPanel';
import AttachmentPanel from '@/app/components/AttachmentPanel';
import CrmCustomFieldsPanel from '@/app/components/CrmCustomFieldsPanel';

async function crm(action,payload){const res=await fetch('/api/crm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}
const money=(value,currency='')=>value==null?'—':`${currency||''} ${Number(value).toLocaleString()}`.trim();

export default function Client360Drawer({client,reference,onClose,onEdit,onRefresh}){
 const[detail,setDetail]=useState(null);const[state,setState]=useState('loading');const[tab,setTab]=useState('overview');const[action,setAction]=useState(null);const[form,setForm]=useState({});
 async function load(){setState('loading');try{setDetail(await crm('client360',{clientId:client.id}));setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[client.id]);
 function begin(type,seed={}){setAction(type);setForm(seed)}
 async function save(){setState('saving');try{
   if(action==='contact')await crm('saveContact',{clientId:client.id,fullName:form.fullName,email:form.email||'',phone:form.phone||'',title:form.title||'',roleType:form.roleType||'OTHER',decisionAuthority:form.decisionAuthority||'UNKNOWN'});
   if(action==='opportunity')await crm('saveOpportunity',{clientId:client.id,name:form.name,estimatedValue:form.estimatedValue||'',currencyCode:form.currencyCode||client.currency_code||'',probability:form.probability||20,expectedCloseDate:form.expectedCloseDate||'',nextAction:form.nextAction||''});
   if(action==='activity')await crm('saveActivity',{clientId:client.id,activityType:form.activityType||'CALL',subject:form.subject||'',body:form.body||'',direction:form.direction||'OUTBOUND',outcome:form.outcome||'',nextAction:form.nextAction||'',nextActionAt:form.nextActionAt||''});
   if(action==='task')await crm('saveTask',{clientId:client.id,title:form.title,description:form.description||'',priority:form.priority||'NORMAL',dueAt:form.dueAt||'',assignedUserId:form.assignedUserId||''});
   if(action==='contract')await crm('saveContract',{clientId:client.id,name:form.name,contractType:form.contractType||'CONTINGENCY',status:form.status||'DRAFT',feeType:form.feeType||'',feePercent:form.feePercent||'',feeAmount:form.feeAmount||'',currencyCode:form.currencyCode||client.currency_code||'',paymentTermsDays:form.paymentTermsDays||'',guaranteeDays:form.guaranteeDays||'',effectiveFrom:form.effectiveFrom||'',effectiveTo:form.effectiveTo||'',exclusivity:Boolean(form.exclusivity),notes:form.notes||''});
   setAction(null);setForm({});await load();onRefresh?.();setState('ready');
 }catch(e){setState(e.message||'error')}}
 const d=detail||{};const metrics=d.metrics||{};
 return <aside className="crm-360-drawer" aria-label="Client 360">
   <div className="crm-drawer-head"><div><span className="page-kicker">Client 360</span><h2>{client.name}</h2><p>{[client.industry,client.city,client.country_code].filter(Boolean).join(' · ')||'Recruitment account'}</p></div><button aria-label="Close" onClick={onClose}>×</button></div>
   <div className="crm-health-strip"><span className={`crm-health ${String(client.health_status||'UNASSESSED').toLowerCase()}`}>{(client.health_status||'UNASSESSED').replaceAll('_',' ')}</span><b>{client.status}</b><small>{client.owner_name?`Owner · ${client.owner_name}`:'Unassigned owner'}</small></div>
   <div className="crm-metric-grid"><div><span>Open jobs</span><b>{metrics.open_jobs||0}</b></div><div><span>Open opportunities</span><b>{metrics.open_opportunities||0}</b></div><div><span>Pipeline</span><b>{money(metrics.pipeline_value,client.currency_code)}</b></div><div><span>Placement fees</span><b>{money(metrics.placement_fees,client.currency_code)}</b></div></div>
   <div className="crm-quick-actions"><button className="primary-action" onClick={()=>begin('opportunity',{currencyCode:client.currency_code||''})}>＋ Opportunity</button><button onClick={()=>begin('contact')}>＋ Contact</button><button onClick={()=>begin('activity')}>Log activity</button><button onClick={()=>begin('task')}>Create task</button><button onClick={onEdit}>Edit account</button></div>
   <div className="crm-tabs">{[['overview','Overview'],['contacts','Contacts'],['opportunities','Opportunities'],['commercial','Revenue & terms'],['activity','Activity'],['custom','Custom fields'],['files','Files & notes']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>
   <div className="crm-drawer-body">
   {tab==='overview'?<><section className="crm-card"><div className="crm-section-title"><div><b>Account intelligence</b><small>One place for commercial and recruitment context</small></div></div><div className="drawer-grid"><div><span>Website</span><b>{client.website||client.domain||'—'}</b></div><div><span>Country</span><b>{client.country_code||'—'}</b></div><div><span>Timezone</span><b>{client.timezone||'—'}</b></div><div><span>Currency</span><b>{client.currency_code||'—'}</b></div><div><span>Lifecycle</span><b>{client.lifecycle_stage||'PROSPECT'}</b></div><div><span>Priority</span><b>{client.priority||'NORMAL'}</b></div></div></section><section className="crm-card next-action-card"><span>Next best action</span><b>{client.next_action||'No next action set'}</b><small>{client.next_action_at?new Date(client.next_action_at).toLocaleString():'Set a task or log an activity to keep momentum visible.'}</small></section><section className="crm-card"><div className="crm-section-title"><div><b>Recruitment footprint</b><small>Jobs currently associated with this account</small></div><span>{d.jobs?.length||0}</span></div>{d.jobs?.length?<div className="crm-compact-list">{d.jobs.slice(0,8).map(j=><article key={j.id}><div><b>{j.title}</b><small>{[j.location,j.country_code].filter(Boolean).join(' · ')}</small></div><span className="status-pill">{j.status}</span></article>)}</div>:<small>No jobs linked yet.</small>}</section></>:null}
   {tab==='contacts'?<section className="crm-card"><div className="crm-section-title"><div><b>Decision-maker map</b><small>Hiring, talent, finance and commercial stakeholders</small></div><button onClick={()=>begin('contact')}>＋ Contact</button></div>{d.contacts?.length?<div className="crm-contact-list">{d.contacts.map(c=><article key={c.id}><div><b>{c.full_name}</b><small>{[c.title,c.department].filter(Boolean).join(' · ')||c.email||'Contact'}</small></div><div><span>{c.role_type?.replaceAll('_',' ')}</span><small>{c.decision_authority?.replaceAll('_',' ')}</small></div></article>)}</div>:<div className="crm-empty">No contacts yet. Add the first hiring or decision-making stakeholder.</div>}</section>:null}
   {tab==='opportunities'?<section className="crm-card"><div className="crm-section-title"><div><b>Business opportunities</b><small>BD pipeline connected to this account</small></div><button onClick={()=>begin('opportunity',{currencyCode:client.currency_code||''})}>＋ Opportunity</button></div>{d.opportunities?.length?<div className="crm-opportunity-list">{d.opportunities.map(o=><article key={o.id}><div><b>{o.name}</b><small>{o.next_action||'No next action'}</small></div><div><b>{money(o.estimated_value,o.currency_code)}</b><span>{o.stage_name}</span></div></article>)}</div>:<div className="crm-empty">No open business opportunity yet.</div>}</section>:null}
   {tab==='commercial'?<><section className="crm-card"><div className="crm-section-title"><div><b>Commercial terms</b><small>Fee and guarantee agreements</small></div><button onClick={()=>begin('contract',{currencyCode:client.currency_code||''})}>＋ Terms</button></div>{d.contracts?.length?<div className="crm-contract-list">{d.contracts.map(c=><article key={c.id}><div><b>{c.name}</b><small>{c.contract_type?.replaceAll('_',' ')} · {c.status}</small></div><div><b>{c.fee_type==='PERCENTAGE'&&c.fee_percent!=null?`${c.fee_percent}%`:money(c.fee_amount,c.currency_code)}</b><small>{c.payment_terms_days!=null?`${c.payment_terms_days}d payment`:''}{c.guarantee_days!=null?` · ${c.guarantee_days}d guarantee`:''}</small></div></article>)}</div>:<small>No commercial terms saved.</small>}</section><section className="crm-card"><div className="crm-section-title"><div><b>Placement revenue</b><small>Durable placement records from the ATS</small></div><span>{d.placements?.length||0}</span></div>{d.placements?.length?<div className="crm-compact-list">{d.placements.map(p=><article key={p.id}><div><b>{p.candidate_name||'Candidate'} → {p.job_title||'Placement'}</b><small>{p.start_date||'Start date pending'}</small></div><b>{money(p.placement_fee,p.fee_currency)}</b></article>)}</div>:<small>No placement revenue yet.</small>}</section></>:null}
   {tab==='activity'?<section className="crm-card"><div className="crm-section-title"><div><b>Relationship timeline</b><small>Calls, emails, meetings and client feedback</small></div><button onClick={()=>begin('activity')}>Log activity</button></div>{d.activities?.length?<div className="crm-activity-list">{d.activities.map(a=><article key={a.id}><i/><div><b>{a.subject||a.activity_type?.replaceAll('_',' ')}</b><p>{a.body||a.outcome||''}</p><small>{new Date(a.occurred_at).toLocaleString()}{a.actor_name?` · ${a.actor_name}`:''}</small></div></article>)}</div>:<div className="crm-empty">No relationship activity recorded yet.</div>}<div className="crm-section-title sub"><div><b>Open follow-ups</b></div><button onClick={()=>begin('task')}>＋ Task</button></div>{d.tasks?.length?<div className="crm-compact-list">{d.tasks.map(t=><article key={t.id}><div><b>{t.title}</b><small>{t.due_at?new Date(t.due_at).toLocaleString():'No due date'}</small></div><span className="status-pill">{t.status}</span></article>)}</div>:<small>No tasks linked.</small>}</section>:null}
   {tab==='custom'?<CrmCustomFieldsPanel entityType="CLIENT" entityId={client.id} definitions={reference?.custom_fields||[]} values={d.custom_values||[]} onSaved={load}/>:null}
   {tab==='files'?<><AttachmentPanel entityType="CLIENT" entityId={client.id} title="Client files"/><NotesPanel entityType="CLIENT" entityId={client.id} title="Account notes"/></>:null}
   </div>
   {action?<div className="crm-action-sheet"><div className="crm-action-head"><div><span className="page-kicker">Fast action</span><h3>{action==='contact'?'Add contact':action==='opportunity'?'Create opportunity':action==='activity'?'Log relationship activity':action==='task'?'Create follow-up task':'Add commercial terms'}</h3></div><button onClick={()=>setAction(null)}>×</button></div>
     {action==='contact'?<div className="form-grid two"><label className="form-control"><span>Full name *</span><input value={form.fullName||''} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label className="form-control"><span>Title</span><input value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="form-control"><span>Email</span><input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span>Phone</span><input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span>Role</span><select value={form.roleType||'OTHER'} onChange={e=>setForm({...form,roleType:e.target.value})}>{['DECISION_MAKER','HIRING_MANAGER','TALENT','HR','PROCUREMENT','FINANCE','EXECUTIVE','TECHNICAL','OTHER'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Authority</span><select value={form.decisionAuthority||'UNKNOWN'} onChange={e=>setForm({...form,decisionAuthority:e.target.value})}>{['UNKNOWN','INFLUENCER','RECOMMENDER','DECISION_MAKER','ECONOMIC_BUYER'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label></div>:null}
     {action==='opportunity'?<div className="form-grid two"><label className="form-control wide"><span>Opportunity name *</span><input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} placeholder={`${client.name} — recruitment opportunity`}/></label><label className="form-control"><span>Estimated value</span><input type="number" min="0" value={form.estimatedValue||''} onChange={e=>setForm({...form,estimatedValue:e.target.value})}/></label><label className="form-control"><span>Currency</span><input maxLength="3" value={form.currencyCode||''} onChange={e=>setForm({...form,currencyCode:e.target.value.toUpperCase()})}/></label><label className="form-control"><span>Probability %</span><input type="number" min="0" max="100" value={form.probability||20} onChange={e=>setForm({...form,probability:e.target.value})}/></label><label className="form-control"><span>Expected close</span><input type="date" value={form.expectedCloseDate||''} onChange={e=>setForm({...form,expectedCloseDate:e.target.value})}/></label><label className="form-control wide"><span>Next action</span><input value={form.nextAction||''} onChange={e=>setForm({...form,nextAction:e.target.value})}/></label></div>:null}
     {action==='activity'?<div className="form-grid two"><label className="form-control"><span>Type</span><select value={form.activityType||'CALL'} onChange={e=>setForm({...form,activityType:e.target.value})}>{['CALL','EMAIL','MEETING','LINKEDIN','WHATSAPP','SMS','CLIENT_FEEDBACK','NOTE','OTHER'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Direction</span><select value={form.direction||'OUTBOUND'} onChange={e=>setForm({...form,direction:e.target.value})}>{['OUTBOUND','INBOUND','INTERNAL'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-control wide"><span>Subject</span><input value={form.subject||''} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label className="form-control wide"><span>Context / outcome</span><textarea rows="4" value={form.body||''} onChange={e=>setForm({...form,body:e.target.value})}/></label><label className="form-control"><span>Next action</span><input value={form.nextAction||''} onChange={e=>setForm({...form,nextAction:e.target.value})}/></label><label className="form-control"><span>Follow-up</span><input type="datetime-local" value={form.nextActionAt||''} onChange={e=>setForm({...form,nextActionAt:e.target.value})}/></label></div>:null}
     {action==='task'?<div className="form-grid two"><label className="form-control wide"><span>Task *</span><input value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="form-control"><span>Priority</span><select value={form.priority||'NORMAL'} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','NORMAL','HIGH','URGENT'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-control"><span>Due</span><input type="datetime-local" value={form.dueAt||''} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label className="form-control"><span>Assignee</span><select value={form.assignedUserId||''} onChange={e=>setForm({...form,assignedUserId:e.target.value})}><option value="">Me</option>{reference?.members?.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="form-control wide"><span>Description</span><textarea rows="3" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>:null}
     {action==='contract'?<div className="form-grid two"><label className="form-control wide"><span>Agreement name *</span><input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="form-control"><span>Type</span><select value={form.contractType||'CONTINGENCY'} onChange={e=>setForm({...form,contractType:e.target.value})}>{['CONTINGENCY','RETAINED','RPO','TEMP_STAFFING','CONTRACT_STAFFING','MASTER_SERVICE','PROJECT','OTHER'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Fee type</span><select value={form.feeType||''} onChange={e=>setForm({...form,feeType:e.target.value})}><option value="">Select</option>{['PERCENTAGE','FIXED','HOURLY_MARKUP','MARGIN','CUSTOM'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Fee %</span><input type="number" min="0" max="100" value={form.feePercent||''} onChange={e=>setForm({...form,feePercent:e.target.value})}/></label><label className="form-control"><span>Fixed fee</span><input type="number" min="0" value={form.feeAmount||''} onChange={e=>setForm({...form,feeAmount:e.target.value})}/></label><label className="form-control"><span>Currency</span><input maxLength="3" value={form.currencyCode||''} onChange={e=>setForm({...form,currencyCode:e.target.value.toUpperCase()})}/></label><label className="form-control"><span>Payment terms (days)</span><input type="number" min="0" value={form.paymentTermsDays||''} onChange={e=>setForm({...form,paymentTermsDays:e.target.value})}/></label><label className="form-control"><span>Guarantee (days)</span><input type="number" min="0" value={form.guaranteeDays||''} onChange={e=>setForm({...form,guaranteeDays:e.target.value})}/></label></div>:null}
     <div className="modal-actions"><span>{state==='saving'?'Saving…':!['ready','loading','saving'].includes(state)?`Could not save: ${state}`:''}</span><button className="primary-action" onClick={save} disabled={state==='saving'||(action==='contact'&&!form.fullName)||(action==='opportunity'&&!form.name)||(action==='task'&&!form.title)||(action==='contract'&&!form.name)}>{state==='saving'?'Saving…':'Save'}</button></div>
   </div>:null}
   {state==='loading'?<div className="drawer-loading">Loading Client 360…</div>:null}
 </aside>
}
