'use client';

import { useState } from 'react';

export default function ClientPortalWorkspace({token,snapshot}){
 const[data,setData]=useState(snapshot);const[state,setState]=useState('idle');const[comments,setComments]=useState({});
 async function feedback(submissionId,decision){setState(`saving:${submissionId}`);try{const res=await fetch('/api/public/client-portal/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token,submissionId,decision,comment:comments[submissionId]||''})});const result=await res.json();if(!res.ok)throw new Error(result.error||'feedback_failed');setData(prev=>({...prev,submissions:(prev.submissions||[]).map(s=>s.id===submissionId?{...s,status:decision==='REQUEST_INTERVIEW'?'INTERVIEW_REQUESTED':decision==='ADVANCE'?'ADVANCED':decision==='REJECT'?'REJECTED':decision==='HOLD'?'ON_HOLD':s.status,feedback:[{decision,comment:comments[submissionId]||'',created_at:new Date().toISOString()},...(s.feedback||[])]}:s)}));setComments(c=>({...c,[submissionId]:''}));setState('saved')}catch(e){setState(e.message||'error')}}
 return <main className="client-portal-shell"><header className="portal-header"><div><span className="page-kicker">Client portal</span><h1>{data?.client?.name||'Recruitment workspace'}</h1><p>Candidate submissions, interviews and live hiring collaboration.</p></div>{data?.contact?<div className="portal-contact"><span>Signed in as</span><b>{data.contact.full_name}</b><small>{data.contact.title||data.contact.email}</small></div>:null}</header>
 <section className="portal-stats"><div><span>Open roles</span><b>{data?.jobs?.length||0}</b></div><div><span>Candidate submissions</span><b>{data?.submissions?.length||0}</b></div><div><span>Interviews</span><b>{data?.interviews?.length||0}</b></div></section>
 <section className="portal-section"><div className="portal-section-head"><div><span className="page-kicker">Candidates</span><h2>Submitted for your review</h2></div><small>Feedback is shared instantly with your recruitment team.</small></div>{data?.submissions?.length?<div className="portal-submissions">{data.submissions.map(s=><article key={s.id} className="portal-submission"><div className="portal-submission-head"><div><b>{s.candidate_name}</b><span>{s.candidate_title||'Candidate'}</span></div><span className="status-pill">{String(s.status||'SUBMITTED').replaceAll('_',' ')}</span></div><div className="portal-submission-grid"><div><span>Role</span><b>{s.job_title}</b></div><div><span>Availability</span><b>{s.availability||'—'}</b></div><div><span>Notice</span><b>{s.notice_period_days!=null?`${s.notice_period_days} days`:'—'}</b></div><div><span>Compensation</span><b>{s.salary_expectation?`${s.salary_currency||''} ${Number(s.salary_expectation).toLocaleString()}`:'—'}</b></div></div>{s.summary?<p className="portal-summary">{s.summary}</p>:null}<label className="portal-comment"><span>Feedback / context</span><textarea rows="3" value={comments[s.id]||''} onChange={e=>setComments({...comments,[s.id]:e.target.value})} placeholder="Add context for the recruitment team…"/></label><div className="portal-feedback-actions"><button onClick={()=>feedback(s.id,'COMMENT')} disabled={state===`saving:${s.id}`}>Comment</button><button onClick={()=>feedback(s.id,'HOLD')} disabled={state===`saving:${s.id}`}>Hold</button><button className="danger-action" onClick={()=>feedback(s.id,'REJECT')} disabled={state===`saving:${s.id}`}>Reject</button><button className="primary-action" onClick={()=>feedback(s.id,'REQUEST_INTERVIEW')} disabled={state===`saving:${s.id}`}>Request interview</button><button className="primary-action secondary" onClick={()=>feedback(s.id,'ADVANCE')} disabled={state===`saving:${s.id}`}>Advance</button></div>{s.feedback?.length?<div className="portal-feedback-history"><b>Recent feedback</b>{s.feedback.slice(0,4).map((f,i)=><small key={`${f.created_at}-${i}`}>{String(f.decision).replaceAll('_',' ')}{f.comment?` · ${f.comment}`:''}</small>)}</div>:null}</article>)}</div>:<div className="portal-empty"><b>No candidate submissions yet.</b><span>Your recruitment team will share candidates here when ready.</span></div>}</section>
 <section className="portal-section"><div className="portal-section-head"><div><span className="page-kicker">Interviews</span><h2>Upcoming and recent interviews</h2></div></div>{data?.interviews?.length?<div className="portal-interviews">{data.interviews.map(i=><article key={i.id}><div><b>{i.candidate_name}</b><small>{i.job_title}</small></div><div><b>{new Date(i.scheduled_at).toLocaleString()}</b><small>{i.timezone} · {String(i.interview_type).replaceAll('_',' ')}</small></div><span className="status-pill">{i.status}</span></article>)}</div>:<div className="portal-empty"><span>No interviews scheduled yet.</span></div>}</section>
 <section className="portal-section"><div className="portal-section-head"><div><span className="page-kicker">Open requirements</span><h2>Current roles</h2></div></div>{data?.jobs?.length?<div className="portal-jobs">{data.jobs.map(j=><article key={j.id}><div><b>{j.title}</b><small>{[j.location,j.country_code,j.workplace_type].filter(Boolean).join(' · ')}</small></div><span>{j.openings||1} opening{Number(j.openings||1)===1?'':'s'}</span></article>)}</div>:<div className="portal-empty"><span>No open roles are currently visible.</span></div>}</section>
 {state==='saved'?<div className="portal-toast">Feedback sent to your recruitment team.</div>:state!=='idle'&&!state.startsWith('saving:')?<div className="portal-toast error">Could not save feedback. Please retry.</div>:null}</main>
}
