'use client';

import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';

async function crm(action,payload){const res=await fetch('/api/crm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}
const names={CLIENT:'Account',CONTACT:'Contact',OPPORTUNITY:'Opportunity',TASK:'Task'};
export default function CrmQuickCreateOverlay({module,reference={},accountOptions=[],countries=[],timezones=[]}){
 const router=useRouter();const[state,setState]=useState('idle');const[form,setForm]=useState(module==='CLIENT'?{name:'',status:'PROSPECT',lifecycleStage:'PROSPECT',healthStatus:'UNASSESSED',priority:'NORMAL',countryCode:'',timezone:'',currencyCode:''}:module==='CONTACT'?{clientId:'',fullName:'',title:'',email:'',phone:'',roleType:'OTHER',decisionAuthority:'UNKNOWN'}:module==='OPPORTUNITY'?{clientId:'',name:'',estimatedValue:'',currencyCode:'',probability:'20',expectedCloseDate:'',nextAction:''}:{clientId:'',title:'',priority:'NORMAL',dueAt:'',assignedUserId:''});
 const zones=useMemo(()=>timezones.filter(z=>!form.countryCode||z.country_code===form.countryCode),[timezones,form.countryCode]);
 function close(){const path=module==='CLIENT'?'/clients':module==='CONTACT'?'/contacts':module==='OPPORTUNITY'?'/opportunities':'/tasks';router.replace(path)}
 async function save(){setState('saving');try{await crm(module==='CLIENT'?'saveClient':module==='CONTACT'?'saveContact':module==='OPPORTUNITY'?'saveOpportunity':'saveTask',form);setState('saved');close();router.refresh()}catch(e){setState(e.message||'error')}}
 const invalid=module==='CLIENT'?!form.name.trim():module==='CONTACT'?(!form.fullName.trim()||!form.clientId):module==='OPPORTUNITY'?(!form.name.trim()||!form.clientId):(!form.title.trim()||!form.clientId);
 return <div className="modal-backdrop quick-create-backdrop"><section className="ats-modal crm-modal quick-create-modal" role="dialog" aria-modal="true" aria-label={`Create ${names[module]}`}><div className="drawer-head"><div><span className="page-kicker">Fast action</span><h2>Create {names[module]}</h2><p>Only essential information now. Enrich the record from its 360° view later.</p></div><button onClick={close}>×</button></div><div className="form-grid two">
 {module==='CLIENT'?<><label className="form-control wide"><span>Account name *</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="form-control"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['PROSPECT','QUALIFIED','ACTIVE','NURTURE'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-control"><span>Country</span><select value={form.countryCode} onChange={e=>setForm({...form,countryCode:e.target.value,timezone:''})}><option value="">Select</option>{countries.map(c=><option key={c.country_code} value={c.country_code}>{c.country_name}</option>)}</select></label><label className="form-control"><span>Timezone</span><select value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}><option value="">Select</option>{zones.map(z=><option key={z.timezone_id} value={z.timezone_id}>{z.display_name}</option>)}</select></label><label className="form-control"><span>Currency</span><input maxLength="3" value={form.currencyCode} onChange={e=>setForm({...form,currencyCode:e.target.value.toUpperCase()})}/></label></>:null}
 {module==='CONTACT'?<><label className="form-control"><span>Account *</span><select autoFocus value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Select account</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="form-control"><span>Full name *</span><input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label className="form-control"><span>Title</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="form-control"><span>Email</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span>Phone</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span>Relationship</span><select value={form.roleType} onChange={e=>setForm({...form,roleType:e.target.value})}>{['DECISION_MAKER','HIRING_MANAGER','TALENT','HR','PROCUREMENT','FINANCE','EXECUTIVE','OTHER'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label></>:null}
 {module==='OPPORTUNITY'?<><label className="form-control"><span>Account *</span><select autoFocus value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Select account</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="form-control"><span>Opportunity name *</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="form-control"><span>Estimated value</span><input type="number" min="0" value={form.estimatedValue} onChange={e=>setForm({...form,estimatedValue:e.target.value})}/></label><label className="form-control"><span>Currency</span><input maxLength="3" value={form.currencyCode} onChange={e=>setForm({...form,currencyCode:e.target.value.toUpperCase()})}/></label><label className="form-control"><span>Probability %</span><input type="number" min="0" max="100" value={form.probability} onChange={e=>setForm({...form,probability:e.target.value})}/></label><label className="form-control"><span>Expected close</span><input type="date" value={form.expectedCloseDate} onChange={e=>setForm({...form,expectedCloseDate:e.target.value})}/></label><label className="form-control wide"><span>Next action</span><input value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})}/></label></>:null}
 {module==='TASK'?<><label className="form-control"><span>Account *</span><select autoFocus value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Select account</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="form-control"><span>Task *</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="form-control"><span>Priority</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','NORMAL','HIGH','URGENT'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-control"><span>Due</span><input type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></label><label className="form-control"><span>Assignee</span><select value={form.assignedUserId} onChange={e=>setForm({...form,assignedUserId:e.target.value})}><option value="">Me</option>{reference.members?.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></>:null}
 </div><div className="modal-actions"><span>{state==='saving'?'Saving…':!['idle','saved'].includes(state)?`Could not save: ${state}`:''}</span><button className="ghost-action" onClick={close}>Cancel</button><button className="primary-action" disabled={invalid||state==='saving'} onClick={save}>{state==='saving'?'Saving…':`Create ${names[module]}`}</button></div></section></div>
}
