'use client';

import { useEffect, useMemo, useState } from 'react';

async function ats(action,payload){const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}

const defaultCriteria=[
 {label:'Role capability',weight:2},{label:'Problem solving',weight:1.5},{label:'Communication',weight:1},{label:'Motivation and fit',weight:1}
];

export default function InterviewScorecardDrawer({interview,onClose,onRefresh}){
 const[context,setContext]=useState(null);const[state,setState]=useState('loading');const[templateId,setTemplateId]=useState('');const[ratings,setRatings]=useState({});const[recommendation,setRecommendation]=useState('');const[comments,setComments]=useState('');const[studio,setStudio]=useState(false);const[template,setTemplate]=useState({name:'Standard interview scorecard',ratingMin:1,ratingMax:5,hidePeerFeedback:true,criteria:defaultCriteria});
 const activeTemplate=useMemo(()=>context?.templates?.find((t)=>t.id===templateId)||context?.templates?.[0]||null,[context,templateId]);
 async function load(){setState('loading');try{const data=await ats('scorecardContext',{interviewId:interview.id,applicationId:interview.application_id});setContext(data);setTemplateId((id)=>id||data.templates?.[0]?.id||'');const mine=data.scorecards?.find((s)=>s.author_user_id===data.current_user_id);if(mine){setTemplateId(mine.template_id||data.templates?.[0]?.id||'');setRecommendation(mine.recommendation||'');setComments(mine.comments||'');setRatings(Object.fromEntries((mine.ratings||[]).map((r)=>[r.criterion_id,{rating:r.rating??'',comment:r.comment||''}]))) }setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[interview?.id]);
 async function submit(submitNow){if(!activeTemplate)return;setState('saving');try{await ats('submitScorecard',{interviewId:interview.id,templateId:activeTemplate.id,ratings:(activeTemplate.criteria||[]).map((c)=>({criterionId:c.id,rating:ratings[c.id]?.rating||null,comment:ratings[c.id]?.comment||''})),recommendation,comments,submit:submitNow});await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 async function saveTemplate(){setState('saving');try{await ats('saveScorecardTemplate',template);setStudio(false);await load();setState('ready')}catch(e){setState(e.message||'error')}}
 function updateCriterion(index,field,value){setTemplate({...template,criteria:template.criteria.map((c,i)=>i===index?{...c,[field]:value}:c)})}
 return <aside className="record-drawer scorecard-drawer" aria-label="Interview scorecard"><div className="drawer-head"><div><span className="page-kicker">Structured interview</span><h2>{interview.candidate_name}</h2><p>{interview.job_title} · {interview.interview_type}</p></div><button onClick={onClose}>×</button></div><div className="drawer-grid"><div><span>Schedule</span><b>{interview.scheduled_at?new Date(interview.scheduled_at).toLocaleString():'—'}</b></div><div><span>Timezone</span><b>{interview.timezone||'—'}</b></div><div><span>Status</span><b>{interview.status}</b></div><div><span>Feedback</span><b>{context?.scorecards?.filter((s)=>s.status==='SUBMITTED').length||0} submitted</b></div></div>
 <section className="closeout-section"><div className="closeout-title"><div><b>Interview scorecard</b><small>Peer feedback stays hidden until submission when the template requires it.</small></div><button className="ghost-action" onClick={()=>setStudio(!studio)}>＋ Template</button></div>{context?.templates?.length?<><label className="form-control"><span>Template</span><select value={templateId} onChange={(e)=>{setTemplateId(e.target.value);setRatings({})}}>{context.templates.map((t)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{activeTemplate?.criteria?.map((c)=><div className="scorecard-criterion" key={c.id}><div><b>{c.label}</b><small>{c.description||`Weight ${c.weight}`}</small></div><select value={ratings[c.id]?.rating??''} onChange={(e)=>setRatings({...ratings,[c.id]:{...ratings[c.id],rating:e.target.value}})}><option value="">Rate</option>{Array.from({length:(activeTemplate.rating_max-activeTemplate.rating_min)+1},(_,i)=>activeTemplate.rating_min+i).map((n)=><option key={n} value={n}>{n}</option>)}</select><input value={ratings[c.id]?.comment||''} onChange={(e)=>setRatings({...ratings,[c.id]:{...ratings[c.id],comment:e.target.value}})} placeholder="Evidence / note"/></div>)}<div className="form-grid"><label className="form-control"><span>Recommendation</span><select value={recommendation} onChange={(e)=>setRecommendation(e.target.value)}><option value="">Select</option>{['STRONG_YES','YES','MIXED','NO','STRONG_NO'].map((v)=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Overall comments</span><textarea rows="4" value={comments} onChange={(e)=>setComments(e.target.value)}/></label></div><div className="drawer-actions"><button onClick={()=>submit(false)}>Save draft</button><button className="primary-action" onClick={()=>submit(true)}>Submit scorecard</button></div></>:<div className="ats-empty"><b>No scorecard template yet.</b><span>Create a standard template to begin structured, comparable interview feedback.</span><button className="primary-action" onClick={()=>setStudio(true)}>Create template</button></div>}</section>
 {studio?<section className="closeout-section template-studio"><div className="closeout-title"><div><b>Scorecard template studio</b><small>Managers can configure reusable weighted criteria.</small></div></div><label className="form-control"><span>Template name</span><input value={template.name} onChange={(e)=>setTemplate({...template,name:e.target.value})}/></label><div className="form-grid two"><label className="form-control"><span>Min rating</span><input type="number" min="0" max="9" value={template.ratingMin} onChange={(e)=>setTemplate({...template,ratingMin:e.target.value})}/></label><label className="form-control"><span>Max rating</span><input type="number" min="2" max="10" value={template.ratingMax} onChange={(e)=>setTemplate({...template,ratingMax:e.target.value})}/></label></div>{template.criteria.map((c,i)=><div className="template-criterion" key={i}><input value={c.label} onChange={(e)=>updateCriterion(i,'label',e.target.value)} placeholder="Criterion"/><input type="number" min="0.1" step="0.1" value={c.weight} onChange={(e)=>updateCriterion(i,'weight',e.target.value)} aria-label="Weight"/><button onClick={()=>setTemplate({...template,criteria:template.criteria.filter((_,x)=>x!==i)})}>×</button></div>)}<button className="ghost-action" onClick={()=>setTemplate({...template,criteria:[...template.criteria,{label:'',weight:1}]})}>＋ Criterion</button><button className="primary-action" disabled={!template.name||!template.criteria.some((c)=>c.label.trim())} onClick={saveTemplate}>Save template</button></section>:null}
 {state==='loading'?<div className="drawer-loading">Loading scorecard…</div>:state!=='ready'&&state!=='saving'?<div className="save-error">Scorecard error: {state}</div>:null}</aside>
}
