'use client';

import { useEffect, useState } from 'react';

async function ats(action,payload){const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}

export default function OfferCloseoutDrawer({offer,onClose,onNewVersion,onRefresh}){
 const[detail,setDetail]=useState(null);const[state,setState]=useState('loading');
 async function load(){setState('loading');try{setDetail(await ats('offerCloseout',{offerId:offer.id}));setState('ready')}catch(e){setState(e.message||'error')}}
 useEffect(()=>{load()},[offer.id]);
 async function approval(action){let note='';if(action==='REJECT')note=prompt('Reason for rejecting this offer approval')||'';setState('saving');try{await ats('offerApproval',{offerId:offer.id,action,note});await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 async function setStatus(status){if(status==='WITHDRAWN'&&!confirm('Withdraw this offer? The status change will be audited.'))return;setState('saving');try{await ats('offerStatus',{offerId:offer.id,status});await load();onRefresh?.();setState('ready')}catch(e){setState(e.message||'error')}}
 const current=detail?.offer||offer;const canApprove=['OWNER','ADMIN'].includes(detail?.role);const pending=(detail?.approvals||[]).some((a)=>a.status==='PENDING');
 return <aside className="record-drawer offer-closeout-drawer"><div className="drawer-head"><div><span className="page-kicker">Offer 360</span><h2>{current.title||'Offer'}</h2><p>{offer.candidate_name||'Candidate'} · {offer.job_title||'Job'} · v{current.version_number||offer.version_number||1}</p></div><button onClick={onClose}>×</button></div>
 <div className="drawer-grid"><div><span>Status</span><b>{current.status}</b></div><div><span>Base</span><b>{current.amount?`${current.currency||''} ${Number(current.amount).toLocaleString()} ${current.salary_period||''}`:'—'}</b></div><div><span>Start</span><b>{current.start_date||'—'}</b></div><div><span>Expiry</span><b>{current.expires_at?new Date(current.expires_at).toLocaleString():'—'}</b></div></div>
 <div className="drawer-actions">{current.status==='DRAFT'?<button className="primary-action" onClick={()=>approval('REQUEST')}>Request approval</button>:null}{pending&&canApprove?<><button className="primary-action" onClick={()=>approval('APPROVE')}>Approve</button><button className="danger-action" onClick={()=>approval('REJECT')}>Reject</button></>:null}{current.status==='APPROVED'?<button className="primary-action" onClick={()=>setStatus('SENT')}>Mark sent</button>:null}{current.status==='SENT'?<button onClick={()=>setStatus('VIEWED')}>Mark viewed</button>:null}{['SENT','VIEWED'].includes(current.status)?<><button className="primary-action" onClick={()=>setStatus('ACCEPTED')}>Accepted</button><button onClick={()=>setStatus('DECLINED')}>Declined</button></>:null}{!['ACCEPTED','DECLINED','WITHDRAWN','EXPIRED'].includes(current.status)?<button className="danger-action" onClick={()=>setStatus('WITHDRAWN')}>Withdraw</button>:null}<button onClick={()=>onNewVersion?.(detail?.root_offer_id||offer.id,current)}>New version</button></div>
 <section className="closeout-section"><div className="closeout-title"><div><b>Approval trail</b><small>Approval decisions are separate durable records.</small></div><span>{detail?.approvals?.length||0}</span></div>{detail?.approvals?.length?<div className="approval-list">{detail.approvals.map((a)=><article key={a.id}><span className="status-pill">{a.status}</span><div><b>Step {a.step_order} · {a.required_role||'Assigned approver'}</b><small>{a.decision_note||'No decision note'}{a.decided_at?` · ${new Date(a.decided_at).toLocaleString()}`:''}</small></div></article>)}</div>:<small>No approval request yet.</small>}</section>
 <section className="closeout-section"><div className="closeout-title"><div><b>Version history</b><small>Every compensation revision remains preserved.</small></div><span>{detail?.versions?.length||0}</span></div>{detail?.versions?.length?<div className="offer-version-list">{detail.versions.map((v)=><article key={v.id} className={v.id===offer.id?'active':''}><div><b>v{v.version_number} · {v.status}</b><small>{v.amount?`${v.currency||''} ${Number(v.amount).toLocaleString()} ${v.salary_period||''}`:'No base compensation'} · {new Date(v.created_at).toLocaleString()}</small></div></article>)}</div>:null}</section>
 {state==='loading'?<div className="drawer-loading">Loading offer…</div>:state!=='ready'&&state!=='saving'?<div className="save-error">Offer error: {state}</div>:null}</aside>
}
