'use client';

import { useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import ApplicationScreeningDrawer from '@/app/components/ApplicationScreeningDrawer';

function transitionMessage(data){
 if(data?.error==='stage_requirements_missing'){
   const missing=Array.isArray(data.missing)?data.missing:[];
   const labels={client:'client',candidate_email:'candidate email',candidate_phone:'candidate phone',candidate_contact:'candidate contact',candidate_timezone:'candidate timezone',candidate_country:'candidate country',candidate_skills:'candidate skills',resume:'CV / resume',screening:'screening',client_submission:'client submission',interview:'interview',scorecard:'submitted scorecard',offer:'offer',approved_offer:'approved offer',placement:'placement record'};
   return `Complete before moving to ${data.stage||'this stage'}: ${missing.map((x)=>labels[x]||String(x).replaceAll('_',' ')).join(', ')}`;
 }
 if(data?.error==='stage_role_forbidden') return `Your role is not allowed to move an application to ${data.stage||'that stage'}.`;
 if(data?.error==='rejection_reason_required') return 'A rejection reason is required for this transition.';
 if(data?.error==='withdrawal_reason_required') return 'A withdrawal reason is required for this transition.';
 return data?.error||'Could not move this application.';
}

export default function PipelineWorkspace({context,candidates=[],jobs=[]}){
 const router=useRouter();const params=useSearchParams();const[form,setForm]=useState({candidateId:params.get('candidate')||'',jobId:params.get('job')||''});const[state,setState]=useState('idle');const[feedback,setFeedback]=useState('');const[reason,setReason]=useState('');const[selected,setSelected]=useState(null);const[view,setView]=useState('board');
 const pipeline=context?.meta?.pipelines?.find((p)=>p.is_default)||context?.meta?.pipelines?.[0];const stages=pipeline?.stages||[];const rows=context?.rows||[];
 const grouped=useMemo(()=>Object.fromEntries(stages.map((s)=>[s.id,rows.filter((r)=>r.stage_id===s.id)])),[stages,rows]);
 async function create(){setState('saving');setFeedback('');const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'createApplication',payload:form})});const data=await res.json().catch(()=>({}));if(!res.ok){setState(data.error||'error');setFeedback(data.error==='application_exists'?'This candidate is already attached to that job.':data.error||'Could not add candidate to job.');return;}setForm({candidateId:'',jobId:''});setState('saved');setFeedback('Candidate added to the recruitment pipeline.');router.refresh()}
 async function move(app,stage){if(!app||!stage||app.stage_id===stage.id)return;const dangerous=stage.code==='REJECTED';let why=reason;if(dangerous&&!why) why=prompt('Rejection reason is required')||'';if(dangerous&&!why)return;setState('saving');setFeedback(`Moving ${app.candidate_name} to ${stage.name}…`);const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'moveApplication',payload:{applicationId:app.id,stageId:stage.id,reason:why||null}})});const d=await res.json().catch(()=>({}));if(res.ok){setState('saved');setReason('');setFeedback(`${app.candidate_name} moved to ${d.stage||stage.name}.`);router.refresh()}else{setState(d.error||'error');setFeedback(transitionMessage(d))}}
 function dragStart(e,app){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/x-xz-application',app.id)}
 function drop(e,stage){e.preventDefault();const id=e.dataTransfer.getData('text/x-xz-application');const app=rows.find((r)=>r.id===id);if(app)move(app,stage)}
 return <div className="ats-workspace"><div className="pipeline-create"><div><span className="page-kicker">Fast action</span><h2>Add candidate to a job</h2><p>One candidate can hold an independent stage, screening record, client submission and interview history for every requisition.</p></div><select value={form.candidateId} onChange={(e)=>setForm({...form,candidateId:e.target.value})}><option value="">Choose candidate</option>{candidates.map((c)=><option key={c.id} value={c.id}>{c.full_name}{c.current_title?` — ${c.current_title}`:''}</option>)}</select><select value={form.jobId} onChange={(e)=>setForm({...form,jobId:e.target.value})}><option value="">Choose job</option>{jobs.map((j)=><option key={j.id} value={j.id}>{j.title}</option>)}</select><button className="primary-action" disabled={!form.candidateId||!form.jobId||state==='saving'} onClick={create}>Add to pipeline</button></div>
 {feedback?<div className={state==='saved'?'pipeline-feedback success':'pipeline-feedback'} role="status" aria-live="polite"><span>{feedback}</span>{state!=='saving'?<button type="button" onClick={()=>setFeedback('')} aria-label="Dismiss message">×</button>:null}</div>:null}
 <div className="pipeline-viewbar"><div><b>{rows.length}</b><span> active applications</span></div><div className="segmented-control"><button className={view==='board'?'active':''} onClick={()=>setView('board')}>Board</button><button className={view==='table'?'active':''} onClick={()=>setView('table')}>Table</button></div></div>
 {view==='board'?<div className="pipeline-board">{stages.map((stage)=><section className="pipeline-column" key={stage.id} onDragOver={(e)=>{e.preventDefault();e.dataTransfer.dropEffect='move'}} onDrop={(e)=>drop(e,stage)}><header><span>{stage.name}</span><b>{grouped[stage.id]?.length||0}</b></header><div className="pipeline-cards">{(grouped[stage.id]||[]).map((app)=><article key={app.id} draggable onDragStart={(e)=>dragStart(e,app)}><button className="pipeline-card-main" onClick={()=>setSelected(app)}><b>{app.candidate_name}</b><span>{app.job_title}</span><small>Entered {app.stage_entered_at?new Date(app.stage_entered_at).toLocaleDateString():'—'} · Application 360 →</small></button><select aria-label={`Move ${app.candidate_name} to another stage`} value={app.stage_id||''} onChange={(e)=>{const target=stages.find((s)=>s.id===e.target.value);if(target)move(app,target)}}><option value={app.stage_id||''}>{stage.name}</option>{stages.filter((s)=>s.id!==app.stage_id).map((s)=><option key={s.id} value={s.id}>Move → {s.name}</option>)}</select></article>)}</div></section>)}</div>:<div className="ats-table-wrap"><table className="ats-table"><thead><tr><th>Candidate</th><th>Job</th><th>Stage</th><th>Entered</th><th>Action</th></tr></thead><tbody>{rows.map((app)=><tr key={app.id} onClick={()=>setSelected(app)}><td><b>{app.candidate_name}</b><small>{app.current_title||''}</small></td><td>{app.job_title}</td><td><span className="status-pill">{app.stage_name||app.stage}</span></td><td>{app.stage_entered_at?new Date(app.stage_entered_at).toLocaleString():'—'}</td><td onClick={(e)=>e.stopPropagation()}><select aria-label={`Move ${app.candidate_name} to another stage`} value={app.stage_id||''} onChange={(e)=>{const target=stages.find((s)=>s.id===e.target.value);if(target)move(app,target)}}><option value={app.stage_id||''}>Move stage</option>{stages.filter((s)=>s.id!==app.stage_id).map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></td></tr>)}</tbody></table></div>}
 {!stages.length?<div className="ats-empty"><b>No recruitment pipeline configured.</b><span>Finish Step-3 pipeline configuration first.</span></div>:null}{selected?<ApplicationScreeningDrawer application={selected} onClose={()=>setSelected(null)} onRefresh={()=>router.refresh()}/>:null}</div>
}
