'use client';

import { useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';

export default function PipelineWorkspace({context,candidates=[],jobs=[]}){
 const router=useRouter();const params=useSearchParams();const[form,setForm]=useState({candidateId:params.get('candidate')||'',jobId:params.get('job')||''});const[state,setState]=useState('idle');const[reason,setReason]=useState('');
 const pipeline=context?.meta?.pipelines?.find((p)=>p.is_default)||context?.meta?.pipelines?.[0];const stages=pipeline?.stages||[];const rows=context?.rows||[];
 const grouped=useMemo(()=>Object.fromEntries(stages.map((s)=>[s.id,rows.filter((r)=>r.stage_id===s.id)])),[stages,rows]);
 async function create(){setState('saving');const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'createApplication',payload:form})});const data=await res.json();if(!res.ok){setState(data.error||'error');return;}setForm({candidateId:'',jobId:''});setState('saved');router.refresh()}
 async function move(app,stage){const dangerous=stage.code==='REJECTED';let why=reason;if(dangerous&&!why) why=prompt('Rejection reason is required')||'';if(dangerous&&!why)return;setState('saving');const res=await fetch('/api/ats',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'moveApplication',payload:{applicationId:app.id,stageId:stage.id,reason:why||null}})});if(res.ok){setState('saved');setReason('');router.refresh()}else{const d=await res.json();setState(d.error||'error')}}
 return <div className="ats-workspace"><div className="pipeline-create"><div><span className="page-kicker">Fast action</span><h2>Add candidate to a job</h2><p>One candidate can hold an independent stage for every requisition.</p></div><select value={form.candidateId} onChange={(e)=>setForm({...form,candidateId:e.target.value})}><option value="">Choose candidate</option>{candidates.map((c)=><option key={c.id} value={c.id}>{c.full_name}{c.current_title?` — ${c.current_title}`:''}</option>)}</select><select value={form.jobId} onChange={(e)=>setForm({...form,jobId:e.target.value})}><option value="">Choose job</option>{jobs.map((j)=><option key={j.id} value={j.id}>{j.title}</option>)}</select><button className="primary-action" disabled={!form.candidateId||!form.jobId||state==='saving'} onClick={create}>Add to pipeline</button>{state==='application_exists'?<small className="save-error">This candidate is already attached to that job.</small>:null}</div>
 <div className="pipeline-board">{stages.map((stage)=><section className="pipeline-column" key={stage.id}><header><span>{stage.name}</span><b>{grouped[stage.id]?.length||0}</b></header><div className="pipeline-cards">{(grouped[stage.id]||[]).map((app)=><article key={app.id}><b>{app.candidate_name}</b><span>{app.job_title}</span><small>Entered {app.stage_entered_at?new Date(app.stage_entered_at).toLocaleDateString():'—'}</small><select value={app.stage_id||''} onChange={(e)=>{const target=stages.find((s)=>s.id===e.target.value);if(target)move(app,target)}}><option value={app.stage_id||''}>{stage.name}</option>{stages.filter((s)=>s.id!==app.stage_id).map((s)=><option key={s.id} value={s.id}>Move → {s.name}</option>)}</select></article>)}</div></section>)}</div>{!stages.length?<div className="ats-empty"><b>No recruitment pipeline configured.</b><span>Finish Step-3 pipeline configuration first.</span></div>:null}</div>
}
