'use client';

import { useState } from 'react';

async function crm(action,payload){const res=await fetch('/api/crm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}

export default function PortalManager({clients=[],vendors=[]}){
 const[state,setState]=useState('idle');const[generated,setGenerated]=useState(null);
 async function clientPortal(client){setState('saving');try{const result=await crm('issueClientPortal',{clientId:client.id});const url=`${location.origin}/portal/client/${result.portal_token}`;await navigator.clipboard?.writeText(url);setGenerated({type:'Client',name:client.name,url,expiresAt:result.expires_at});setState('saved')}catch(e){setState(e.message||'error')}}
 async function vendorPortal(vendor){setState('saving');try{const result=await crm('issueVendorPortal',{vendorId:vendor.id});const url=`${location.origin}/portal/vendor/${result.portal_token}`;await navigator.clipboard?.writeText(url);setGenerated({type:'Vendor',name:vendor.name,url,expiresAt:result.expires_at});setState('saved')}catch(e){setState(e.message||'error')}}
 return <div className="portal-manager"><section className="portal-manager-hero"><div><span className="page-kicker">External collaboration</span><h2>Secure portals without exposing your workspace</h2><p>Generate time-limited links for clients and approved sourcing partners. Every token is stored as a hash and expires automatically.</p></div><div className="portal-manager-security"><span>✓ Time-limited</span><span>✓ Tenant scoped</span><span>✓ No workspace login shared</span></div></section>
 {generated?<section className="portal-generated"><div><span>{generated.type} portal ready</span><b>{generated.name}</b><code>{generated.url}</code><small>Copied to clipboard · expires {generated.expiresAt?new Date(generated.expiresAt).toLocaleString():'automatically'}</small></div><button onClick={()=>{navigator.clipboard?.writeText(generated.url);setState('saved')}}>Copy again</button></section>:null}
 <div className="portal-manager-grid"><section className="crm-card"><div className="crm-section-title"><div><b>Client portals</b><small>Candidate review, interview visibility and structured feedback</small></div><span>{clients.length}</span></div>{clients.length?<div className="portal-manager-list">{clients.map(c=><article key={c.id}><div><b>{c.name}</b><small>{[c.industry,c.city,c.country_code].filter(Boolean).join(' · ')||c.status}</small></div><div><span className="status-pill">{c.status}</span><button className="primary-action" disabled={state==='saving'} onClick={()=>clientPortal(c)}>Create link</button></div></article>)}</div>:<div className="crm-empty">No client or prospect accounts are available yet.</div>}</section><section className="crm-card"><div className="crm-section-title"><div><b>Vendor portals</b><small>Share selected open roles and receive controlled candidate submissions</small></div><span>{vendors.length}</span></div>{vendors.length?<div className="portal-manager-list">{vendors.map(v=><article key={v.id}><div><b>{v.name}</b><small>{v.vendor_type?.replaceAll('_',' ')||'Vendor partner'}</small></div><div><span className="status-pill">{v.status}</span><button className="primary-action" disabled={state==='saving'||v.status!=='ACTIVE'} onClick={()=>vendorPortal(v)}>Create link</button></div></article>)}</div>:<div className="crm-empty">No vendor partners configured yet.</div>}</section></div>{!['idle','saving','saved'].includes(state)?<div className="save-error">Portal action failed: {state}</div>:null}</div>
}
