'use client';

import { useRef, useState } from 'react';

const MAX_BYTES=8*1024*1024;

export default function PublicApplyForm({slug,job}){
 const[state,setState]=useState('idle');const[result,setResult]=useState(null);const[file,setFile]=useState(null);const[fileError,setFileError]=useState('');const fileRef=useRef(null);const[form,setForm]=useState({fullName:'',email:'',phone:'',currentTitle:'',location:'',city:'',countryCode:job?.country_code||'',timezone:'',resumeText:'',consent:false});
 function chooseFile(next){setFileError('');if(!next){setFile(null);return;}if(next.size>MAX_BYTES){setFile(null);setFileError('Resume must be 8 MB or smaller.');if(fileRef.current)fileRef.current.value='';return;}setFile(next)}
 async function submit(e){e.preventDefault();if(!form.consent){setState('consent_required');return;}setState('saving');setResult(null);const body=new FormData();body.append('slug',slug);body.append('payload',JSON.stringify(form));if(file)body.append('file',file);let res;try{res=await fetch('/api/public/apply',{method:'POST',body})}catch{setState('network_error');return;}const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok){setState(data.error||'error');return;}setResult(data);setState('done')}
 if(state==='done')return <div className="public-success" role="status"><b>Application received.</b><span>Your submission has been added securely to the recruiter's workspace.</span>{file&&result?.resumeUploaded?<span>Your CV / resume was stored privately and queued for recruiter review.</span>:null}{file&&!result?.resumeUploaded?<span className="save-error">Your application was received, but the resume file could not be attached. The recruiter still has your application details.</span>:null}{result?.resumeParseStatus==='FAILED'?<small>The resume file is attached, but automatic extraction needs manual recruiter review.</small>:null}</div>;
 return <form className="public-apply" onSubmit={submit}><div className="form-grid two"><label className="form-control"><span>Full name *</span><input required autoComplete="name" value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})}/></label><label className="form-control"><span>Email *</span><input required type="email" autoComplete="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span>Phone</span><input autoComplete="tel" value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span>Current title</span><input autoComplete="organization-title" value={form.currentTitle} onChange={(e)=>setForm({...form,currentTitle:e.target.value})}/></label><label className="form-control wide"><span>Location</span><input autoComplete="address-level2" value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></label><label className="form-control wide"><span>CV / Resume</span><input ref={fileRef} type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={(e)=>chooseFile(e.target.files?.[0]||null)}/><small>PDF, DOCX or TXT · max 8 MB · stored privately</small>{file?<small className="save-good">Selected: {file.name}</small>:null}{fileError?<small className="save-error">{fileError}</small>:null}</label><label className="form-control wide"><span>Profile summary (optional)</span><textarea rows="6" value={form.resumeText} onChange={(e)=>setForm({...form,resumeText:e.target.value})} placeholder="Add a concise experience summary if useful"/></label></div><label className="consent-line"><input required type="checkbox" checked={form.consent} onChange={(e)=>setForm({...form,consent:e.target.checked})}/><span>I consent to this recruitment agency processing the information I submit for this application.</span></label><button className="primary-action" disabled={!form.fullName||!form.email||!form.consent||Boolean(fileError)||state==='saving'}>{state==='saving'?'Submitting securely…':'Submit application'}</button>{state!=='idle'&&state!=='saving'?<span className="save-error" role="alert">{state==='already_applied'?'You already applied for this role.':state==='consent_required'?'Consent is required before submitting this application.':state==='resume_storage_not_configured'?'Resume upload is temporarily unavailable. Please try again later or submit without a file.':state==='unsupported_file_type'?'Use a PDF, DOCX or TXT resume.':state==='invalid_file_size'?'Resume must be 8 MB or smaller.':'Could not submit. Please review your details and try again.'}</span>:null}</form>
}
