'use client';

import { useState } from 'react';

export default function PublicApplyForm({slug,job}){
 const[state,setState]=useState('idle');const[form,setForm]=useState({fullName:'',email:'',phone:'',currentTitle:'',location:'',city:'',countryCode:job?.country_code||'',timezone:'',resumeText:'',consent:false});
 async function submit(e){e.preventDefault();setState('saving');const res=await fetch('/api/public/apply',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug,payload:form})});const data=await res.json();setState(res.ok?'done':data.error||'error')}
 if(state==='done')return <div className="public-success"><b>Application received.</b><span>Your submission has been added securely to the recruiter's workspace.</span></div>;
 return <form className="public-apply" onSubmit={submit}><div className="form-grid two"><label className="form-control"><span>Full name *</span><input required value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})}/></label><label className="form-control"><span>Email *</span><input required type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span>Phone</span><input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span>Current title</span><input value={form.currentTitle} onChange={(e)=>setForm({...form,currentTitle:e.target.value})}/></label><label className="form-control wide"><span>Location</span><input value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></label><label className="form-control wide"><span>Resume / profile summary</span><textarea rows="8" value={form.resumeText} onChange={(e)=>setForm({...form,resumeText:e.target.value})} placeholder="Paste resume text or a concise experience summary"/></label></div><label className="consent-line"><input type="checkbox" checked={form.consent} onChange={(e)=>setForm({...form,consent:e.target.checked})}/><span>I consent to this recruitment agency processing the information I submit for this application.</span></label><button className="primary-action" disabled={!form.fullName||!form.email||state==='saving'}>{state==='saving'?'Submitting…':'Submit application'}</button>{state!=='idle'&&state!=='saving'?<span className="save-error">{state==='already_applied'?'You already applied for this role.':'Could not submit. Please review your details and try again.'}</span>:null}</form>
}
