'use client';

import { useMemo,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
import NotesPanel from '@/app/components/NotesPanel';
import AttachmentPanel from '@/app/components/AttachmentPanel';

async function crm(action,payload){const res=await fetch('/api/crm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}

export default function VendorWorkspace({context,reference,countries=[],timezones=[],jobs=[]}){
 const router=useRouter();const params=useSearchParams();const rows=context?.rows||[];const total=Number(context?.total||0);const page=Math.max(1,Number(params.get('page')||1));const limit=Number(context?.limit||50);const totalPages=Math.max(1,Math.ceil(total/limit));const[query,setQuery]=useState(params.get('q')||'');const[selected,setSelected]=useState(null);const[mode,setMode]=useState(null);const[state,setState]=useState('idle');const[form,setForm]=useState({});const[portalUrl,setPortalUrl]=useState('');
 const zones=useMemo(()=>timezones.filter(z=>!form.countryCode||z.country_code===form.countryCode),[timezones,form.countryCode]);
 function create(){setMode('create');setSelected(null);setPortalUrl('');setForm({name:'',vendorType:'SOURCING_PARTNER',status:'ACTIVE',website:'',email:'',phone:'',countryCode:'',timezone:'',currencyCode:'',ownerUserId:'',specialties:[]})}
 function edit(v){setSelected(v);setMode('edit');setPortalUrl('');setForm({id:v.id,name:v.name||'',vendorType:v.vendor_type||'SOURCING_PARTNER',status:v.status||'ACTIVE',website:v.website||'',email:v.email||'',phone:v.phone||'',countryCode:v.country_code||'',timezone:v.timezone||'',currencyCode:v.currency_code||'',ownerUserId:v.owner_user_id||'',specialties:Array.isArray(v.specialties)?v.specialties:[]})}
 async function save(){setState('saving');try{await crm('saveVendor',form);setMode(null);setState('saved');router.refresh()}catch(e){setState(e.message||'error')}}
 async function issuePortal(){if(!selected)return;setState('saving');try{const result=await crm('issueVendorPortal',{vendorId:selected.id});const url=`${location.origin}/portal/vendor/${result.portal_token}`;setPortalUrl(url);await navigator.clipboard?.writeText(url);setState('portal')}catch(e){setState(e.message||'error')}}
 async function share(jobId,active=true){if(!selected||!jobId)return;setState('saving');try{await crm('shareJobVendor',{vendorId:selected.id,jobId,active});setState('saved')}catch(e){setState(e.message||'error')}}
 function search(e){e.preventDefault();const p=new URLSearchParams();if(query.trim())p.set('q',query.trim());router.push(`/vendors${p.toString()?`?${p}`:''}`)}
 function gotoPage(next){const p=new URLSearchParams();if(query.trim())p.set('q',query.trim());if(next>1)p.set('page',String(next));router.push(`/vendors?${p}`)}
 return <div className="crm-workspace vendor-workspace"><div className="ats-toolbar"><form className="ats-search" onSubmit={search}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search vendor name or email"/><button>Search</button></form><button className="primary-action" onClick={create}>＋ Vendor</button></div><div className="ats-summary"><b>{total}</b><span>vendors</span><small>Sourcing partners · secure portal access · shared jobs · submission visibility</small></div><div className="ats-table-wrap"><table className="ats-table"><thead><tr><th>Vendor</th><th>Type</th><th>Status</th><th>Country</th><th>Shared jobs</th><th>Submissions</th><th>Owner</th><th></th></tr></thead><tbody>{rows.map(v=><tr key={v.id} onClick={()=>{setSelected(v);setMode(null);setPortalUrl('')}}><td><b>{v.name}</b><small>{v.email||v.website||'Vendor partner'}</small></td><td>{v.vendor_type?.replaceAll('_',' ')}</td><td><span className="status-pill">{v.status}</span></td><td>{v.country_code||'—'}</td><td>{v.shared_jobs||0}</td><td>{v.submissions||0}</td><td>{v.owner_name||'—'}</td><td><button className="row-action" onClick={e=>{e.stopPropagation();edit(v)}}>Edit</button></td></tr>)}</tbody></table>{!rows.length?<div className="ats-empty"><b>No vendors yet.</b><span>Add a sourcing or staffing partner when you are ready to collaborate.</span><button className="primary-action" onClick={create}>Create vendor</button></div>:null}</div>{totalPages>1?<div className="table-pagination"><button disabled={page<=1} onClick={()=>gotoPage(page-1)}>← Previous</button><span>{(page-1)*limit+1}–{Math.min(page*limit,total)} of {total}</span><button disabled={page>=totalPages} onClick={()=>gotoPage(page+1)}>Next →</button></div>:null}
 {selected&&!mode?<aside className="crm-360-drawer compact"><div className="crm-drawer-head"><div><span className="page-kicker">Vendor 360</span><h2>{selected.name}</h2><p>{selected.vendor_type?.replaceAll('_',' ')}</p></div><button onClick={()=>setSelected(null)}>×</button></div><div className="crm-health-strip"><span className="status-pill">{selected.status}</span><small>{selected.owner_name?`Owner · ${selected.owner_name}`:'Unassigned owner'}</small></div><div className="drawer-grid"><div><span>Email</span><b>{selected.email||'—'}</b></div><div><span>Phone</span><b>{selected.phone||'—'}</b></div><div><span>Country</span><b>{selected.country_code||'—'}</b></div><div><span>Timezone</span><b>{selected.timezone||'—'}</b></div><div><span>Shared jobs</span><b>{selected.shared_jobs||0}</b></div><div><span>Submissions</span><b>{selected.submissions||0}</b></div></div><div className="crm-quick-actions"><button className="primary-action" onClick={issuePortal}>Create portal link</button><button onClick={()=>edit(selected)}>Edit vendor</button></div>{portalUrl?<div className="portal-link-box"><b>Vendor portal link copied</b><code>{portalUrl}</code><small>Expires automatically in 14 days.</small></div>:null}<section className="crm-card"><div className="crm-section-title"><div><b>Share open jobs</b><small>Only explicitly shared jobs appear in the vendor portal.</small></div></div><div className="vendor-job-share">{jobs.slice(0,30).map(j=><article key={j.id}><div><b>{j.title}</b><small>{[j.location,j.country_code].filter(Boolean).join(' · ')}</small></div><button onClick={()=>share(j.id,true)}>Share</button></article>)}</div></section><AttachmentPanel entityType="VENDOR" entityId={selected.id} title="Vendor files"/><NotesPanel entityType="VENDOR" entityId={selected.id} title="Vendor notes"/>{state==='portal'?<small className="save-good">Secure portal link copied.</small>:!['idle','saved','saving','portal'].includes(state)?<small className="save-error">Vendor action failed: {state}</small>:null}</aside>:null}
 {mode?<div className="modal-backdrop"><section className="ats-modal crm-modal"><div className="drawer-head"><div><span className="page-kicker">{mode==='create'?'Fast create':'Vendor 360'}</span><h2>{mode==='create'?'New vendor':'Edit vendor'}</h2></div><button onClick={()=>setMode(null)}>×</button></div><div className="form-grid two"><label className="form-control wide"><span>Vendor name *</span><input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="form-control"><span>Type</span><select value={form.vendorType||'SOURCING_PARTNER'} onChange={e=>setForm({...form,vendorType:e.target.value})}>{['SOURCING_PARTNER','SUBCONTRACTOR','RPO_PARTNER','STAFFING_PARTNER','FREELANCE_RECRUITER','OTHER'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Status</span><select value={form.status||'ACTIVE'} onChange={e=>setForm({...form,status:e.target.value})}>{['PROSPECT','ACTIVE','SUSPENDED','INACTIVE'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-control"><span>Email</span><input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span>Phone</span><input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span>Website</span><input value={form.website||''} onChange={e=>setForm({...form,website:e.target.value})}/></label><label className="form-control"><span>Country</span><select value={form.countryCode||''} onChange={e=>setForm({...form,countryCode:e.target.value,timezone:''})}><option value="">Select</option>{countries.map(c=><option key={c.country_code} value={c.country_code}>{c.country_name}</option>)}</select></label><label className="form-control"><span>Timezone</span><select value={form.timezone||''} onChange={e=>setForm({...form,timezone:e.target.value})}><option value="">Select</option>{zones.map(z=><option key={z.timezone_id} value={z.timezone_id}>{z.display_name}</option>)}</select></label><label className="form-control"><span>Currency</span><input maxLength="3" value={form.currencyCode||''} onChange={e=>setForm({...form,currencyCode:e.target.value.toUpperCase()})}/></label><label className="form-control"><span>Owner</span><select value={form.ownerUserId||''} onChange={e=>setForm({...form,ownerUserId:e.target.value})}><option value="">Me / current</option>{reference?.members?.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><div className="modal-actions"><span>{state==='saving'?'Saving…':!['idle','saved'].includes(state)?`Could not save: ${state}`:''}</span><button className="primary-action" disabled={!form.name||state==='saving'} onClick={save}>Save vendor</button></div></section></div>:null}</div>
}
