'use client';

import { useMemo,useRef,useState } from 'react';

const MAX_BYTES=8*1024*1024;
export default function VendorPortalWorkspace({token,snapshot}){
 const[data,setData]=useState(snapshot);const[state,setState]=useState('idle');const[selectedJob,setSelectedJob]=useState(snapshot?.jobs?.[0]?.id||'');const[form,setForm]=useState({candidateName:'',candidateEmail:'',candidatePhone:'',currentTitle:'',location:'',summary:''});const[file,setFile]=useState(null);const[fileError,setFileError]=useState('');const fileRef=useRef(null);
 const job=useMemo(()=>data?.jobs?.find(j=>j.id===selectedJob)||null,[data?.jobs,selectedJob]);
 function chooseFile(next){setFileError('');if(!next){setFile(null);return;}if(next.size>MAX_BYTES){setFile(null);setFileError('CV / Resume must be 8 MB or smaller.');if(fileRef.current)fileRef.current.value='';return;}setFile(next)}
 async function submit(e){e.preventDefault();if(!selectedJob||!form.candidateName.trim()||fileError)return;setState('saving');try{const body=new FormData();body.append('token',token);body.append('payload',JSON.stringify({jobId:selectedJob,...form}));if(file)body.append('file',file);const res=await fetch('/api/public/vendor-portal/submit',{method:'POST',body});const result=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(result.error||'submit_failed');setData(prev=>({...prev,submissions:[{id:result.id,job_id:selectedJob,candidate_name:form.candidateName,current_title:form.currentTitle,location:form.location,status:result.status,submitted_at:new Date().toISOString(),resume_attached:Boolean(result.resumeUploaded)},...(prev.submissions||[])]}));setForm({candidateName:'',candidateEmail:'',candidatePhone:'',currentTitle:'',location:'',summary:''});setFile(null);if(fileRef.current)fileRef.current.value='';setState(result.status==='DUPLICATE'?'duplicate':file&&!result.resumeUploaded?'saved_resume_warning':'saved')}catch(e){setState(e.message||'error')}}
 return <main className="vendor-portal-shell"><header className="portal-header"><div><span className="page-kicker">Vendor portal</span><h1>{data?.vendor?.name||'Recruitment partner'}</h1><p>Only jobs explicitly shared with your organization are visible here.</p></div><span className="status good">Secure partner access</span></header>
 <section className="portal-stats"><div><span>Shared roles</span><b>{data?.jobs?.length||0}</b></div><div><span>Your submissions</span><b>{data?.submissions?.length||0}</b></div><div><span>Country</span><b>{data?.vendor?.country_code||'Global'}</b></div></section>
 <section className="vendor-portal-grid"><article className="portal-section"><div className="portal-section-head"><div><span className="page-kicker">Shared requirements</span><h2>Open roles</h2></div></div>{data?.jobs?.length?<div className="vendor-shared-jobs">{data.jobs.map(j=><button key={j.id} className={selectedJob===j.id?'active':''} onClick={()=>setSelectedJob(j.id)}><div><b>{j.title}</b><small>{[j.location,j.country_code,j.workplace_type].filter(Boolean).join(' · ')}</small></div><span>{j.employment_type?.replaceAll('_',' ')||'Open'}</span></button>)}</div>:<div className="portal-empty"><b>No roles shared right now.</b><span>Your recruitment agency will share jobs here when collaboration is needed.</span></div>}</article>
 <article className="portal-section vendor-submit-panel"><div className="portal-section-head"><div><span className="page-kicker">Candidate submission</span><h2>{job?job.title:'Select a role'}</h2></div></div>{job?<form onSubmit={submit} className="vendor-candidate-form"><div className="form-grid two"><label className="form-control"><span>Candidate name *</span><input required value={form.candidateName} onChange={e=>setForm({...form,candidateName:e.target.value})}/></label><label className="form-control"><span>Email</span><input type="email" value={form.candidateEmail} onChange={e=>setForm({...form,candidateEmail:e.target.value})}/></label><label className="form-control"><span>Phone</span><input value={form.candidatePhone} onChange={e=>setForm({...form,candidatePhone:e.target.value})}/></label><label className="form-control"><span>Current title</span><input value={form.currentTitle} onChange={e=>setForm({...form,currentTitle:e.target.value})}/></label><label className="form-control wide"><span>Location</span><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label className="form-control wide"><span>CV / Resume</span><input ref={fileRef} type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={e=>chooseFile(e.target.files?.[0]||null)}/><small>PDF, DOCX or TXT · max 8 MB · stored in private recruitment storage</small>{file?<small className="save-good">Selected: {file.name}</small>:null}{fileError?<small className="save-error">{fileError}</small>:null}</label><label className="form-control wide"><span>Candidate summary</span><textarea rows="7" maxLength="8000" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} placeholder="Relevant skills, experience, availability and why this candidate fits the role."/></label></div><button className="primary-action" disabled={state==='saving'||!form.candidateName.trim()||Boolean(fileError)}>{state==='saving'?'Submitting securely…':'Submit candidate'}</button>{state==='saved'?<small className="save-good">Candidate submitted securely{file?' with private resume.':'.'}</small>:state==='saved_resume_warning'?<small className="save-error">Candidate was submitted, but the resume attachment could not be stored. The agency still received the candidate details.</small>:state==='duplicate'?<small className="save-good">Candidate was already present for this role; the agency received a duplicate-review signal.</small>:state==='resume_storage_not_configured'?<small className="save-error">Private resume upload is not configured yet. Submit without a file or contact the recruitment agency.</small>:!['idle','saving'].includes(state)?<small className="save-error">Could not submit candidate. Please retry.</small>:null}</form>:<div className="portal-empty">Select a shared role before submitting a candidate.</div>}</article></section>
 <section className="portal-section"><div className="portal-section-head"><div><span className="page-kicker">Submission history</span><h2>Your recent candidates</h2></div></div>{data?.submissions?.length?<div className="vendor-submission-history">{data.submissions.map(s=><article key={s.id}><div><b>{s.candidate_name}</b><small>{s.current_title||s.location||'Candidate'}{s.resume_attached?' · CV attached':''}</small></div><span className="status-pill">{String(s.status).replaceAll('_',' ')}</span><small>{new Date(s.submitted_at).toLocaleString()}</small></article>)}</div>:<div className="portal-empty"><span>No candidates submitted yet.</span></div>}</section></main>
}
