'use client';

import { useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
async function crm(action,payload){const res=await fetch('/api/crm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,payload})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data?.error||'request_failed');return data}
export default function VendorQuickCreateOverlay({reference={},countries=[],timezones=[]}){
 const router=useRouter();const[state,setState]=useState('idle');const[form,setForm]=useState({name:'',vendorType:'SOURCING_PARTNER',status:'ACTIVE',email:'',phone:'',countryCode:'',timezone:'',currencyCode:'',ownerUserId:''});const zones=useMemo(()=>timezones.filter(z=>!form.countryCode||z.country_code===form.countryCode),[timezones,form.countryCode]);
 function close(){router.replace('/vendors')}
 async function save(){setState('saving');try{await crm('saveVendor',form);setState('saved');close();router.refresh()}catch(e){setState(e.message||'error')}}
 return <div className="modal-backdrop quick-create-backdrop"><section className="ats-modal crm-modal quick-create-modal" role="dialog" aria-modal="true"><div className="drawer-head"><div><span className="page-kicker">Fast action</span><h2>Create Vendor</h2><p>Add the partner now; share roles and issue portal access from Vendor 360°.</p></div><button onClick={close}>×</button></div><div className="form-grid two"><label className="form-control wide"><span>Vendor name *</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="form-control"><span>Type</span><select value={form.vendorType} onChange={e=>setForm({...form,vendorType:e.target.value})}>{['SOURCING_PARTNER','SUBCONTRACTOR','RPO_PARTNER','STAFFING_PARTNER','FREELANCE_RECRUITER','OTHER'].map(v=><option key={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="form-control"><span>Email</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="form-control"><span>Phone</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="form-control"><span>Country</span><select value={form.countryCode} onChange={e=>setForm({...form,countryCode:e.target.value,timezone:''})}><option value="">Select</option>{countries.map(c=><option key={c.country_code} value={c.country_code}>{c.country_name}</option>)}</select></label><label className="form-control"><span>Timezone</span><select value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}><option value="">Select</option>{zones.map(z=><option key={z.timezone_id} value={z.timezone_id}>{z.display_name}</option>)}</select></label><label className="form-control"><span>Currency</span><input maxLength="3" value={form.currencyCode} onChange={e=>setForm({...form,currencyCode:e.target.value.toUpperCase()})}/></label><label className="form-control"><span>Owner</span><select value={form.ownerUserId} onChange={e=>setForm({...form,ownerUserId:e.target.value})}><option value="">Me</option>{reference.members?.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><div className="modal-actions"><span>{state==='saving'?'Saving…':!['idle','saved'].includes(state)?`Could not save: ${state}`:''}</span><button className="ghost-action" onClick={close}>Cancel</button><button className="primary-action" disabled={!form.name.trim()||state==='saving'} onClick={save}>Create vendor</button></div></section></div>
}
