import Link from 'next/link';

const Brand = () => <div className="brand" aria-label="XZ Recruiter"><img className="brand-logo" src="/xzrecruiter-logo.png" alt="XZ Recruiter" width="205" height="30" /></div>;

export default function Home(){
  return <main>
    <div className="shell"><nav className="nav"><Brand/><div className="navlinks"><a href="#product">Product</a><a href="#workflow">Workflow</a><a href="#security">Security</a><a href="#pricing">Pricing</a></div><div className="actions"><Link className="btn ghost" href="/login">Sign in</Link><Link className="btn primary" href="/signup">Start free</Link></div></nav></div>
    <section className="hero"><div className="shell"><div className="eyebrow"><span className="dot"/>Hiring intelligence built for recruitment agencies</div><h1>Know <em>who is hiring</em> before your competitors do.</h1><p>XZRecruiter turns live hiring signals into a ranked business-development radar — with evidence, urgency, fit, and the next action your team should take.</p><div className="hero-actions"><Link href="/signup" className="btn primary">Launch your 14-day pilot →</Link><a href="#product" className="btn">See the product</a></div><div className="proof"><span><b>Evidence-first</b> company signals</span><span><b>Explainable</b> Hiring Heat</span><span><b>Agency-ready</b> workflow</span><span><b>India + global</b> markets</span></div></div></section>
    <div className="shell" id="product"><div className="product-frame"><div className="window"><div className="topbar"><span className="circle"/><span className="circle"/><span className="circle"/></div><div className="screen"><aside className="sidebar"><div className="side-item active">Today’s Radar</div><div className="side-item">Companies</div><div className="side-item">Jobs & signals</div><div className="side-item">Clients</div><div className="side-item">Candidates</div><div className="side-item">Pipeline</div><div className="side-item">Reports</div></aside><section className="mainpane"><div className="pane-head"><div><h3>Today’s Radar</h3><small style={{color:'#788496'}}>Best companies to contact right now</small></div><span className="badge">● Signals fresh</span></div><div className="metrics"><div className="metric"><small>Hot accounts</small><strong>18</strong></div><div className="metric"><small>Fresh roles</small><strong>74</strong></div><div className="metric"><small>High-fit</small><strong>31</strong></div><div className="metric"><small>New today</small><strong>12</strong></div></div>{[['Northstar Labs','92','88','Fresh security team expansion'],['Aperture Cloud','87','91','4 roles posted in 48h'],['Meridian Systems','83','86','Hiring velocity up 2.4×']].map((r)=><div className="radar-row" key={r[0]}><div className="co"><strong>{r[0]}</strong><small>Cybersecurity · Mid-market</small></div><div className="heat">{r[1]}</div><div className="score">{r[2]}% fit</div><div className="signal">{r[3]}</div></div>)}</section></div></div></div></div>
    <section className="section" id="workflow"><div className="shell"><h2>From noisy job data to a clear BD decision.</h2><p className="section-lead">XZRecruiter continuously normalizes hiring activity, removes stale noise, scores agency fit, and explains why an account deserves attention now.</p><div className="grid3"><div className="card"><div className="icon">01</div><h3>Detect real hiring intent</h3><p>Monitor public ATS and careers data, normalize duplicates, identify freshness, and separate genuine expansion from stale reposts.</p></div><div className="card"><div className="icon">02</div><h3>Rank by Hiring Heat</h3><p>Blend urgency, freshness, trust and your agency’s niche fit into one explainable priority score — never a mystery black box.</p></div><div className="card"><div className="icon">03</div><h3>Turn signals into revenue</h3><p>Save, watchlist, contact and advance target companies through your BD workflow while measuring meetings, clients and placements.</p></div></div></div></section>
    <section className="section" id="security"><div className="shell"><h2>Built to keep client and candidate data private.</h2><p className="section-lead">Server-only database access, secure HTTP-only sessions, restricted runtime credentials, row-level security at the data API layer, audit-ready architecture and security headers by default.</p></div></section>
    <section className="section" id="pricing"><div className="shell"><h2>Start with the signal. Upgrade when it pays.</h2><p className="section-lead">14-day pilot for one niche and up to 100 tracked companies. Production plans are designed around Solo, Pro and Agency teams.</p><div className="cta"><div><h2>Make tomorrow’s outreach list in minutes.</h2><p>Create your agency workspace, define the market you recruit in, and let XZRecruiter prioritize the companies worth contacting.</p></div><Link className="btn primary" href="/signup">Start free →</Link></div></div></section>
    <footer className="footer"><div className="shell">© 2026 XZRecruiter · XZ TechLabs · Hiring intelligence for modern recruitment teams.</div></footer>
  </main>
}
